### ISSUE TITLE
关于数据集的构造

### ISSUE THREAD

**Issue by Sally6651** [OFA-Sys/Chinese-CLIP#100]
您好！我目前有一个疑问，能不能自己造一些图片
样本，比如.png的格式，能否直接改成您这边的数据集要求格式，当做训练集重新训练模型？

**Comment by yangapku** [comment]
您好，当然是可以的。如果使用自己的数据集，请您参考readme "教程-跨模态检索-准备工作-数据集格式预处理"部分，把自己的原始图片-文本对数据转成最终使用的LMDB格式。

**Comment by Sally6651** [comment]
您好，能不能提供一下运算的脚本？

**Comment by yangapku** [comment]
您好，readme对应部分已经给出了全部的流程，需要的代码都在repo中哈，没有额外的脚本了
