### ISSUE TITLE
请问demo中的图到图检索是如何实现的？

### ISSUE THREAD

**Issue by yourfathermyson** [OFA-Sys/Chinese-CLIP#105]
我想实现图到图减速，但不知道怎么弄

**Comment by yangapku** [comment]
您好，根据readme的描述，我们图到图和文到图检索，都是先使用Chinese-CLIP产出特征，之后基于开源代码库 clip-retrieval（https://github.com/rom1504/clip-retrieval）实现的，可以仔细参考下如何用这个代码库搭建demo哈，这个代码库本身也提供了一个检索页面的样例（https://rom1504.github.io/clip-retrieval/）。我们的前端界面和这个ui有点不同，是由modelscope的同学帮我们在前端又封装了下，但是背后调用服务还是使用这个代码库哈。

**Comment by BIGBALLON** [comment]
@yangapku Hi, 您好，请问Chinese-CLIP产出的特征可以直接被[clip-retrieval](https://github.com/rom1504/clip-retrieval)使用吗，还是需要进行额外的转换，请问您是怎么做的呢，谢谢
