### ISSUE TITLE
请问demo中的图文检索的图片库是哪个，我希望能构建一个类似的

### ISSUE THREAD

**Issue by 6Roy** [OFA-Sys/Chinese-CLIP#107]

**Comment by yangapku** [comment]
您好，demo的图片检索库，主要是WIT数据集的Wikipedia图片（https://github.com/google-research-datasets/wit），以及少量的laion5b中文part训练数据哈。

**Comment by 6Roy** [comment]
作者大大，我原本希望直接像您一样构建一个检索数据库，完成长文本检索图片的需求从而得到匹配的图片，但由于硬盘有限，我现在希望使用selenium去爬取您构建的modelscope中demo的图片，但是我在模拟输入文本，text_box = ***@***.***="textbox"]')，但是始终无法找到元素，是网站设置了不能爬取图片的机制么，麻烦作者了。


龙行天下
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] 请问demo中的图文检索的图片库是哪个，我希望能构建一个类似的 (Issue #107)





 
您好，demo的图片检索库，主要是WIT数据集的Wikipedia图片（https://github.com/google-research-datasets/wit ），以及少量的laion5b中文part训练数据哈。

**Comment by yangapku** [comment]
您好，这一点确实我也不是很清楚了。demo前端是modelscope的同学帮我们开发的，我们只负责背后基于clip-retrieval开源库的服务搭建哈。

**Comment by duyz1234** [comment]
> 作者大大，我原本希望直接像您一样构建一个检索数据库，完成长文本检索图片的需求从而得到匹配的图片，但由于硬盘有限，我现在希望使用selenium去爬取您构建的modelscope中demo的图片，但是我在模拟输入文本，text_box = ***@***.***="textbox"]')，但是始终无法找到元素，是网站设置了不能爬取图片的机制么，麻烦作者了。 龙行天下 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "OFA-Sys/Chinese-CLIP" ***@***.***&gt;; 发送时间:&nbsp;2023年5月15日(星期一) 上午10:49 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] 请问demo中的图文检索的图片库是哪个，我希望能构建一个类似的 (Issue #107) 您好，demo的图片检索库，主要是WIT数据集的Wikipedia图片（https://github.com/google-research-datasets/wit ），以及少量的laion5b中文part训练数据哈。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，这个问题您这边有解决吗？

**Comment by yangapku** [comment]
您好，建议还是从上面我们回复的图片库来源，直接下载图片哈，就不用考虑反爬的问题了。
