### ISSUE TITLE
 LMDB格式文件 不区分train test valid

### ISSUE THREAD

**Issue by kukuhaza** [OFA-Sys/Chinese-CLIP#109]
请问如果我不想区分train test valid 而生成 LMDB 需要怎样操作呢？

**Comment by DtYXs** [comment]
您好，我理解是可以把所有数据都处理到`train_imgs.tsv`和`train_texts.jsonl`，在执行`python cn_clip/preprocess/build_lmdb_dataset.py`的时候`--splits`只传入`train`

**Comment by kukuhaza** [comment]
好主意ㅜㅜ 谢谢您！
