### ISSUE TITLE
关于bert.pooler

### ISSUE THREAD

**Issue by 1180300528** [OFA-Sys/Chinese-CLIP#11]
我在下载预训练模型之后，直接调用eval下的extract_features.py时加载模型显示我缺失bert.pooler相关参数（Missing key(s) in state_dict: "bert.pooler.dense.weight", "bert.pooler.dense.bias"），我看到代码里对这一部分进行了强调（sd = {k[len('module.'):]: v for k, v in sd.items() if "bert.pooler" not in k}），但我没有发现解决这一问题的办法，请问对于这一部分为什么会代码中进行强调，以及该如何解决这一问题呢？？？

**Comment by yangapku** [comment]
**您好，请您更新一下我们repo最新的代码（尤其是modeling_bert.py）再试试哈。** 具体来说，bert.pooler是中文roberta模型实现中自带的一个模块（我们文本侧encoder使用中文roberta），但这个模块我们的CLIP并不需要用到。因此我们在近期更新的代码中，已经在模型实现modeling_bert.py中去掉了这个模块的定义，同时也将之前公开的参数ckpt文件移除了里面的bert.pooler参数值。您列出的这一行代码，主要是为了让最新的模型代码，还能够兼容大家之前已经下载的含有bert.pooler参数值的ckpt，在读取ckpt的时候能自动忽略掉里面bert.pooler的部分。但是如果使用更新前的代码，去load新的ckpt，可能就会报您这里的错误了，这个就需要您更新下最新代码来解决了。
