### ISSUE TITLE
如何继续之前的训练

### ISSUE THREAD

**Issue by T0305** [OFA-Sys/Chinese-CLIP#110]
请问权重读取相关选项中的reset-data-offset该如何使用？

**Comment by yangapku** [comment]
您好，reset-data-offset一般是我们从预训练切换到finetune时使用的，目的是让模型继续训练时，不按照已训练步数跳过训练数据。从预训练切换到finetune时，训练数据集整个都不同了，所以我们不跳过任何finetune数据，所以我们在我们提供的脚本中加上了reset-data-offset（以及reset-optimizer）。如果是finetune中断了要继续训练，在batch size不变的前提下，因为我们想要跳过之前已经见过的训练数据，所以reset-data-offset就不使用了。另外，reset-optimizer也不打开，让模型读取优化器状态继续训练。

**Comment by yangapku** [comment]
您好，reset-data-offset一般是我们从预训练切换到finetune时使用的，目的是让模型继续训练时，不按照已训练步数跳过训练数据。从预训练切换到finetune时，训练数据集整个都不同了，所以我们不跳过任何finetune数据，所以我们在我们提供的脚本中加上了reset-data-offset（以及reset-optimizer）。如果是finetune中断了要继续训练，在batch size不变的前提下，因为我们想要跳过之前已经见过的训练数据，所以reset-data-offset就不使用了。另外，reset-optimizer也不打开，让模型读取优化器状态继续训练。

**Comment by T0305** [comment]
回答的很详细，十分感谢！

**Comment by applesleam** [comment]
> 您好，reset-data-offset一般是我们从预训练切换到finetune时使用的，目的是让模型继续训练时，不按照已训练步数跳过训练数据。从预训练切换到finetune时，训练数据集整个都不同了，所以我们不跳过任何finetune数据，所以我们在我们提供的脚本中加上了reset-data-offset（以及reset-optimizer）。如果是finetune中断了要继续训练，在batch size不变的前提下，因为我们想要跳过当前epoch之前已经见过的finetune训练数据，所以reset-data-offset就不使用了，让训练代码读取已经训练的步数，定位到应该继续训练的训练集data offset。另外，reset-optimizer也不打开，让模型读取优化器状态继续训练。

您好！我发现在训练被中断后resume时，数据仍然会从当前epoch从头开始读取（没有设置reset-data-offset的情况下），而不是从“此前的数据断点续跑”，看起来配置reset-data-offset只会保证resume训练中加载的每个epoch的shuffle顺序与上次相同，并不能跳过当前epoch已经训练过的数据，上面这段解释和参数的注释是否会造成误解？或是我的理解还不够清楚？还请帮忙解答下～感谢🙏

**Comment by yangapku** [comment]
@applesleam 您好，您指出的确实是我们的一个代码问题哈。这个跳过的逻辑似乎在我们内部代码中存在，但是开源过程中没有merge进来，目前确实还是会从一个epoch的开头读取的。我们会尽量分配精力，尽快补上这个跳过的feature哈。

**Comment by applesleam** [comment]
了解了，感谢回复！
