### ISSUE TITLE
同一batch中出现同一类的情况

### ISSUE THREAD

**Issue by michelleweii** [OFA-Sys/Chinese-CLIP#111]
DataLoader时会考虑同一个batch中出现同一个文本的情况吗？
比如{text: image_id}的样式， {金刚3:3892}，{金刚3:5398} 是两个正pair，被加载到同入一个batch中，会出现将 {金刚3:5398} 当做负pair的情况，但这是错误的。

我看代码里使用DistributedSampler采样器，有解决这个问题吗？

**Comment by yangapku** [comment]
目前我们处理上，在预处理时会把图文多对多（或一对多/多对一）的情况，拆成多个一对一的图文对用于训练。由于训练中对图文对会进行shuffle，shuffle的随机性减缓了相同图像或文本的样例出现在一个batch。同时我们在多卡global batch上计算对比学习损失，batch如果开大些，能学习的负例也比较多，相对这个因素造成的因素就会小一些了。目前Chinese-CLIP在预训练和汇报的下游任务上，简单起见没有再进行更多这方面的特殊处理，您也可以在目前的基础上继续优化数据处理和采样流程，可能会有更好的提升~

**Comment by michelleweii** [comment]
你好，感谢解答。
关于“batch如果开大些，能学习的负例也比较多，相对这个因素造成的因素就会小一些了” 的理解，想再请教一点，是我理解有误吗？

比如图文多对一的情况，真实样本：
{金刚3: 3892}，
{金刚3: 5398}，
{金刚3: 123}，
{金刚3: 456}，
{金刚3: 789}，
{金刚3: 10111}

如果batchsize小一点，那么6个样本进入同一batch的情况难道不是小一点吗？
如果batchsize很大，那么6个样本进入同一batch的几率越大，但是论文里矩阵上只有对角线的是正例，
因此对于 {金刚3: 3892} 这个对角线的正例来说，{金刚3: 5398}、{金刚3: 123}、{金刚3: 456}等等在矩阵里，{金刚3: 3892}行的位置上都被当做负例学习了。但他们其实也是正例。

**Comment by yangapku** [comment]
您好，这里的意思是假定在这些样本都误进入了一个batch的前提下，如果我们的batch size非常大（比如几k样本），每个训练图文对样本的负例非常多，此时这些负例中几个正例被当做负例造成的影响就很小了。

**Comment by michelleweii** [comment]
好的，谢谢
