### ISSUE TITLE
Windows系统下微调

### ISSUE THREAD

**Issue by T0305** [OFA-Sys/Chinese-CLIP#114]
$ bash run_scripts/flickr30k_finetune_rn50_rbt-base.sh ../DATAPATH/
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as
needed.
*****************************************
Traceback (most recent call last):
  File "cn_clip/training/main.py", line 16, in <module>
    from cn_clip.clip import load
ModuleNotFoundError: No module named 'cn_clip'
Traceback (most recent call last):
  File "cn_clip/training/main.py", line 16, in <module>
    from cn_clip.clip import load
ModuleNotFoundError: No module named 'cn_clip'
Killing subprocess 7480
Killing subprocess 9048
Traceback (most recent call last):
  File "C:\Users\HP\.conda\envs\clip\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\.conda\envs\clip\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\.conda\envs\clip\lib\site-packages\torch\distributed\launch.py", line 340, in <module>
    main()
  File "C:\Users\HP\.conda\envs\clip\lib\site-packages\torch\distributed\launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "C:\Users\HP\.conda\envs\clip\lib\site-packages\torch\distributed\launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\HP\\.conda\\envs\\clip\\python.exe', '-u', 'cn_clip/training/main.py', '--train-data=../DATAPATH//datasets/Flickr30k-CN/lmdb/train', '--val-data=../
DATAPATH//datasets/Flickr30k-CN/lmdb/valid', '--resume=../DATAPATH//pretrained_weights/clip_cn_rn50.pt', '--reset-data-offset', '--reset-optimizer', '--logs=../DATAPATH//experiments/', '--name=flickr30
k_finetune_rn50_rbt3_2gpu', '--save-step-frequency=999999', '--save-epoch-frequency=1', '--log-interval=1', '--report-training-batch-acc', '--context-length=52', '--warmup=100', '--batch-size=64', '--v
alid-batch-size=64', '--valid-step-interval=150', '--valid-epoch-interval=1', '--accum-freq=1', '--lr=2e-6', '--wd=0.001', '--max-epochs=16', '--vision-model=RN50', '--use-augment', '--text-model=RBT3-
chinese']' returned non-zero exit status 1.
py文件中的from cn_clip一直报红，试着改了路径的调用方式也一直没成功，请问能帮忙看一下吗？

**Comment by DtYXs** [comment]
您好，或许您可以尝试运行`pip install cn_clip`看一下报错是否还存在。我们目前没有进行过Windows系统下的微调实验，之前有过Windows系统与NCCL的支持问题的相关Issuehttps://github.com/OFA-Sys/Chinese-CLIP/issues/57供您参考。更建议您在Linux系统下进行训练~

**Comment by T0305** [comment]
感谢您的回复，我换用Linux系统下进行训练了。另外我想请问我微调后的pt文件可以再进行训练吗？

**Comment by DtYXs** [comment]
可以的，把`--resume`参数改为微调后的pt文件路径就可以了

**Comment by T0305** [comment]
非常感谢您的回复！
下面是我微调Flickr30k-CN数据集时设置的参数：
GPUS_PER_NODE=1
WORKER_CNT=1context_length=52
warmup=100
batch_size=128
valid_batch_size=128
accum_freq=1
lr=2e-6
wd=0.001
max_epochs=16
valid_step_interval=150
valid_epoch_interval=1
vision_model=RN50
text_model=RBT3-chinese
use_augment="--use-augment"
在进行到第10个epoch时，loss值降到了0.67左右，到最后剩下的epoch里也一直保持在0.67附近，请问我这是在已经拟合的现象了吗？最终评估R1结果和您们提供的相差了2%左右，R5和R10都相差了1%左右。

**Comment by DtYXs** [comment]
您好哈，根据您的loss和Recall结果看模型应该是已经拟合了。1%左右的差距应该已经比较小了，您可以参考我们的[技术报告](https://arxiv.org/pdf/2211.01335.pdf)中给出的超参数配置。根据您给出的超参数看您可能是在单卡上finetune的，单卡上的finetune我们尝试的不是特别多，也欢迎您分享您在单卡上取得较好结果的超参数配置哈。
