### ISSUE TITLE
some problems with reproduction experiment

### ISSUE THREAD

**Issue by Noobb123** [OFA-Sys/Chinese-CLIP#116]
I was recently finetuning  FLICKR 30K on CN_CLIP as described in the paper , but the results are quite different from the indicators on the paper.
Could you provide the fine-tuning model file of Flickr30k in the paper? I would like to find my own problem through the parameter distribution,thanks!

**Comment by yangapku** [comment]
Hi, could you please specify the model size (base, large, large-336 or huge) you would like us to share? Meanwhile, we have provided all the fine-tuning hyper-params in the appendix of our paper. You could also check the difference between you configuration and us.
