### ISSUE TITLE
请问这个模型是同时支持中文和英文吗？

### ISSUE THREAD

**Issue by xxaier** [OFA-Sys/Chinese-CLIP#117]
如题

**Comment by yangapku** [comment]
您好，模型主要是支持中文的，因为预训练模型是英文CLIP视觉侧初始化的，且预训练数据中也含有少量英文数据，所以也能够支持部分英文的case

**Comment by xxaier** [comment]
请问没有有具体的评测数据，英文向量的准确率和召回率和原始的clip相比如何？
因为我想做一个搜索stable-diffusion生成图片的网站，想同时支持中文和英文搜索（网站有中文版和英文版）。
现在在考虑两种方案，一种是先把中文翻译成为英文再去向量搜索，还有一种方案是用clip，我想确认下哪一种更合适。

**Comment by ldfandian** [comment]
> 您好，模型主要是支持中文的，因为预训练模型是英文CLIP视觉侧初始化的，且预训练数据中也含有少量英文数据，所以也能够支持部分英文的case

训练的2亿数据里应该也包含不少英文的训练数据吧？难道训练的时候全部被剔除出去了？

**Comment by yangapku** [comment]
@ldfandian 您好，训练数据是本身就是中文来源的（来自laion的部分有laion本身提供的语言识别标注，我们也是选的中文语言的部分），英文数据是非常少的。

**Comment by xxaier** [comment]
我最后找到了这个
https://github.com/FlagAI-Open/FlagAI/tree/master/examples/AltCLIP-m18
继双语模型AltCLIP与9语模型AltCLIP-m9之后，我们训练了18语CLIP模型。命名为AltCLIP-m18。它支持英语、中文、日语、泰语、韩语、印地语、乌克兰语、阿拉伯语、土耳其语、越南语、波兰语、荷兰语、葡萄牙语、意大利语、西班牙语、德语、法语和俄语。

AltCLIP-m18模型可以为AltDiffusion-m18模型提供支持
