### ISSUE TITLE
关于多机多卡训练

### ISSUE THREAD

**Issue by mantianlong** [OFA-Sys/Chinese-CLIP#12]
你好，我用2台4卡A100训练1个epoch时间在10h，单机4卡A100一个epoch的训练时间30min。请问哪些地方导致多机多卡训练效率降低的？

**Comment by yangapku** [comment]
您好，由于目前我们的多卡训练默认打开了aggregate（由训练配置中的`--skip-aggregate`控制），在模型输出侧会进行一次机器间**all-gather的通信操作**，把每张卡上的local batch通过通信聚合成global batch，从而计算负样本更多的对比学习损失。这个操作是比较消耗通信带宽的，所以可能会受限于机器间网络通信性能上，最优的配置是机器间**通信网络支持RDMA通信**，这样训练的加速比会好很多。

**Comment by yangapku** [comment]
请参见https://github.com/OFA-Sys/Chinese-CLIP/blob/2746589ee1c9fce925d3b4f70c767e99de47610f/cn_clip/training/train.py#L25-L33

**Comment by mantianlong** [comment]
懂了，赞👍🏻，谢谢~
