### ISSUE TITLE
关于训练的数据准备

### ISSUE THREAD

**Issue by duyz1234** [OFA-Sys/Chinese-CLIP#122]
您好！我在尝试自己准备数据集，如图所示
<img width="274" alt="78e09e32709bc572cd12ed1c4c666af" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/132811872/706c6ce0-46ff-4f13-969e-63def60bc195">
在执行： python cn_clip/preprocess/build_lmdb_dataset.py --data_dir Chinese-CLIP/DATA/datasets/CH-1/test/  --splits train的时候出现如下报错：
<img width="858" alt="c73d2b4ae00d595d68ffe7e4a6ea283" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/132811872/80638196-fd38-45d2-a7ac-b5d91a2a6154">
<img width="830" alt="e068f8777c0e099ebcb657726a5f682" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/132811872/63b3b4f0-0c52-4a9f-b948-6510c596f2d1">

这种我该如何解决呢

**Comment by DtYXs** [comment]
您好，建议您可以再根据[数据集格式预处理](https://github.com/OFA-Sys/Chinese-CLIP#%E6%95%B0%E6%8D%AE%E9%9B%86%E6%A0%BC%E5%BC%8F%E9%A2%84%E5%A4%84%E7%90%86)中的目录检查一下文件。
您可以再检查一下xxx_texts.jsonl文件中是否每一行都是一个完整的json格式数据。
另外根据您的报错，您可以在cn_clip/preprocess/build_lmdb_dataset.py第64行附近添加一些print来输出一下目前程序读取的`line`和`field`分别具体是什么，来帮助判断一下问题。
