### ISSUE TITLE
请教一个问题，训练cn-clip的时候，为什么没有同时使用laion-5b的所有中英文数据，而只使用中文？

### ISSUE THREAD

**Issue by ldfandian** [OFA-Sys/Chinese-CLIP#123]
是担心训练时间过长了么？
还是担心visual encoder or text encoder本身的多语言表达能力不够好？

**Comment by yangapku** [comment]
您好，确实有担心训练时间过长的考虑，因为我们的训练资源也比较有限。另一方面，也比较担心加入较多英文图文数据，对于中文case的下游效果有影响，考虑到我们的文本encoder是用中文roberta初始化，同时中文和英文的数据domain也有一定的区别。后续如果我们还有富余的资源，也会继续在多语言的方面进行探索哈。

**Comment by xxaier** [comment]
可以看下这个
https://github.com/FlagAI-Open/FlagAI/tree/master/examples/AltCLIP-m18

AltCLIP-m18。它支持英语、中文、日语、泰语、韩语、印地语、乌克兰语、阿拉伯语、土耳其语、越南语、波兰语、荷兰语、葡萄牙语、意大利语、西班牙语、德语、法语和俄语。
