### ISSUE TITLE
怎样将该模型转换成pytorchscript格式的模型？

### ISSUE THREAD

**Issue by zhangjh** [OFA-Sys/Chinese-CLIP#127]
我是一个后端工程师，对AI不算很熟，请问如何将你们的模型转换成torchscript格式的模型？我需要部署在手机端，目前只找到支持这个格式的方案。

**Comment by yangapku** [comment]
您好，目前在部署侧我们还没有支持torchscript格式，支持的是ONNX和tensorRT格式的部署方案。未来如果有精力我们会优先考虑这个需求哈。

**Comment by zhangjh** [comment]
好的感谢，我研究下onnx的

**Comment by huishaocpdd** [comment]
现在有支持torchscript格式了吗
