### ISSUE TITLE
在处理Laion2B-multi中文数据时，用了BLIP论文里的CapFilt方法来优化数据质量么？

### ISSUE THREAD

**Issue by ldfandian** [OFA-Sys/Chinese-CLIP#128]
CapFilt主要是去把原始素材里的Noisy描述去掉，提升质量~

![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/5018331/5993930e-8fd8-4c82-b70f-9373e73951f6)

**Comment by yangapku** [comment]
您好，我们整体做法比较简单~直接使用了部分规则筛选数据，具体细节已经在技术报告paper中说明，没有使用CapFilt哈。如果您有这方面的实验结论，欢迎基于中文CLIP继续探究！
