### ISSUE TITLE
grad-checkpointing error

### ISSUE THREAD

**Issue by mynameischaos** [OFA-Sys/Chinese-CLIP#13]
Hi an~ @yangapku 

When I set the parameter 'grad-checkpointing' to True, but report this error:
----------
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.

Do you have any suggestions to solve this problem?

**Comment by yangapku** [comment]
您好，您可以参考这个帖子 https://discuss.pytorch.org/t/finding-the-cause-of-runtimeerror-expected-to-mark-a-variable-ready-only-once/124428/5 ，将pytorch升级到1.9.0及以上版本后，运行前设置环境变量`export TORCH_DISTRIBUTED_DEBUG=INFO`，这样报错将显示详细的有问题的参数名。您可以将详细报错回复我们进行后续排查。

**Comment by yangapku** [comment]
您是在我们代码的基础上，有自己的改动吗？可以看下model的forward call之外，哪里还用到了`bert.encoder.layer.11.output.LayerNorm.weight`这个参数。如果外面必须要用到它，可以考虑把这个参数乘上1.0作为model forward call的一个返回值，然后外面用这个返回值即可。

**Comment by on1you** [comment]
遇到了同样的问题
v100单机单卡:  pytorch2.0.0+cu117

`GPUS_PER_NODE=1
WORKER_CNT=1
export MASTER_ADDR=localhost
export MASTER_PORT=8514
export RANK=0 
export TORCH_DISTRIBUTED_DEBUG=INFO`

只要grad-checkpointing=True就跑不起来，错误信息如下：
`2023-04-04,18:17:25 | INFO | Rank 0 | Global Steps: 1/588 | Train Epoch: 1 [128/25088 (1%)] | Loss: 1.903587 | Image2Text Acc: 57.03 | Text2Image Acc: 49.22 | Data Time: 2.576s | Batch Time: 8.592s | LR: 0.000000 | logit_scale: 4.605 | Global Batch Size: 128
Traceback (most recent call last):
  File "cn_clip/training/main.py", line 298, in <module>
    main()
  File "cn_clip/training/main.py", line 246, in main
    num_steps_this_epoch = train(model, data, epoch, optimizer, scaler, scheduler, args, steps)
  File "/data/notebook/chinese-clip/cn_clip/training/train.py", line 145, in train
    total_loss, acc = get_loss(model, images, texts, loss_img, loss_txt, args)
  File "/data/notebook/chinese-clip/cn_clip/training/train.py", line 22, in get_loss
    image_features, text_features, logit_scale = model(images, texts, args.mask_ratio)
  File "/data/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 0: bert.encoder.layer.11.output.dense.bias, bert.encoder.layer.11.output.dense.weight, bert.encoder.layer.11.intermediate.dense.bias, bert.encoder.layer.11.intermediate.dense.weight, bert.encoder.layer.11.attention.output.dense.bias, bert.encoder.layer.11.attention.output.dense.weight, bert.encoder.layer.11.attention.self.value.bias, bert.encoder.layer.11.attention.self.value.weight, bert.encoder.layer.11.attention.self.key.bias, bert.encoder.layer.11.attention.self.key.weight, bert.encoder.layer.11.attention.self.query.bias, bert.encoder.layer.11.attention.self.query.weight
Parameter indices which did not receive grad for rank 0: 479 480 481 482 483 484 485 486 489 490 491 492
Exception in thread Thread-1:
Traceback (most recent call last):
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 `

按提示find_unused_parameters=True也不行

**Comment by Stubborn-one** [comment]
pytorch2.0遇到同样问题，换成1.12就好使了

**Comment by yangapku** [comment]
您好，我们近期更新了代码，提高了对于pytorch2.0的兼容性，目前pytorch2.0已经可以正常使用gradient checkpointing了哈
