### ISSUE TITLE
可以告知如何在java下调用模型的API来生成文本或图像特征码？

### ISSUE THREAD

**Issue by zhangjh** [OFA-Sys/Chinese-CLIP#131]
已经按照deploy文档将模型转换成了onnx格式，我目的是在安卓或者java技术栈下使用。
现在卡在不知道如何使用onnx来调用api，文档给出的都是python示例，请问如何在java下调用，有人知道吗？

**Comment by yangapku** [comment]
您好，这方面我们确实也不是很了解，没有相关的经验了。我理解我们onnx的格式应该是比较标准的，可以从onnx官方网站寻求一些相关资料吗？

**Comment by zhangjh** [comment]
作者你好，经过我这几天频繁的研究摸索，翻遍了谷歌，在ChatGpt的强力辅助下，我已经把模型在java环境下跑通了。
模型我转换好后，使用了vit-b-16-txt/img.fp32.onnx的模型，因为fp16的转换后有两份，一份带ext_file后缀，加载fp16模型的时候会报错，不知道有没有关系。
关于文本特征向量的提取没有问题了，正确性也验证过了，但是图片的特征提取不符合预期，我做不出来文档提供的正确率。
我检查了很多遍，我的java代码实现基本是跟文档给出的步骤是完全一致的，但是图文相似性数值差的非常多，比如“皮卡丘”和“pokemon.jpeg”图片的相似度，文档是9.4504e-01，而我用普通的余弦相似度算法计算式0.3834404594635363
，而用文档给出的先计算矩阵内积，再计算softmax的方式，结果永远是[1.0]。。。
我将我的实现代码核心部分贴在这里，一方面作者如果发现哪里有问题可以帮忙指出(基本就是文档python代码实现的java版实现，主要用到了nd4j)，另一方面也给其他想将模型移植到Java/Android的同学一些参考，少走一些弯路。
```
1. 图片预处理，省略resize、convertToRgb
private OnnxTensor toTensor(BufferedImage image, OrtEnvironment env) throws OrtException {
        float[] imageData = new float[image.getWidth() * image.getHeight() * 3];
        int pixelIdx = 0;
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                int rgb = image.getRGB(x, y);
                imageData[pixelIdx++] = ((rgb >> 16) & 0xFF) / 255.0f; // R
                imageData[pixelIdx++] = ((rgb >> 8) & 0xFF) / 255.0f; // G
                imageData[pixelIdx++] = (rgb & 0xFF) / 255.0f; // B
            }
        }
        // Normalize the image
        float[] mean = new float[] {0.48145466f, 0.4578275f, 0.40821073f};
        float[] std = new float[] {0.26862954f, 0.26130258f, 0.27577711f};
        for (int i = 0; i < imageData.length; i++) {
            imageData[i] = (imageData[i] - mean[i % 3]) / std[i % 3];
        }

        // Create and return the ONNX tensor [1,3,224,224]
        long[] shape = new long[] {1, 3, image.getHeight(), image.getWidth()};
        FloatBuffer data = FloatBuffer.wrap(imageData);
        return OnnxTensor.createTensor(env, data, shape);
    }
2. onnx核心调用部分，预处理包含了上述resize、convertToRgb、toTensor、归一化等
    OnnxTensor inputTensor = preprocess(bufferedImage, 224, ortEnv);

        Map<String, OnnxTensor> inputMap = new HashMap<>();
        inputMap.put("image", inputTensor);
        OrtSession.Result result = session.run(inputMap);

        float[] outputData = ((float[][]) result.get(0).getValue())[0];
        INDArray imageFeatures = Nd4j.create(outputData, new int[]{1, outputData.length});

        // 归一化
        INDArray norm = imageFeatures.norm2(-1).reshape(imageFeatures.size(0), 1);
        INDArray normalizedImageFeatures = imageFeatures.div(norm);
        return normalizedImageFeatures.data().asFloat();

3. 计算特征向量相似性：先将特征向量转矩阵，内积后求softmax
        INDArray imageFeaturesArr = Nd4j.createFromArray(tmp1);
        INDArray textFeaturesArr = Nd4j.createFromArray(tmp2);

        // 计算图文相似概率
        INDArray logitsPerImage = imageFeaturesArr.mmul(textFeaturesArr.transpose()).mul(100);
        INDArray softmax = Transforms.softmax(logitsPerImage, true);
```
"皮卡丘"文本提取的特征向量：
`[0.12005333, -0.009177025, -0.0348875, 0.024505993, -0.029932057, 0.008274428, 0.031804446, 0.034996796, -0.0161692, -0.024424624, -0.026299186, -0.04646894, -0.01686606, 0.012166081, -0.03814663, 0.029805254, 0.042995237, -0.055837553, 0.04582072, 0.07784319, 5.799507E-5, 0.03833097, -0.025716277, -0.012393091, 0.018495193, -0.009262578, 0.0020483104, 0.014889839, -0.04180662, 0.070689686, 0.009371544, 0.0140230935, -0.025096722, 0.09963658, 0.036962643, 0.014789317, 0.0071994043, -0.003398851, 0.0152715575, -0.043159693, -0.020216316, -0.022095699, 0.020986808, 0.038757175, 0.012962977, -0.012999322, 0.052465808, 0.009547763, 0.026862698, -0.018305093, 0.029267129, -0.0026488663, -0.049486417, -0.004048671, -0.0010010466, -0.039696205, -0.008532647, 0.056644585, -0.055446174, -0.0050047296, -0.0030697307, 0.029964238, -0.036727186, -0.052102637, -9.1192283E-4, -0.043734018, 0.006610903, -0.014565771, 0.06945917, -0.013574764, 0.014422923, 6.096773E-4, -0.010038248, 0.006935369, 0.015373987, -0.041129023, -0.016137859, -0.007156055, -0.008154612, -0.0033983204, 0.017817095, 0.029253747, -0.036483232, -0.026651805, 0.04916128, 0.0037411565, 0.031023376, -0.064421564, -0.011360418, -0.01565239, -0.044451598, 9.928752E-4, 0.08580389, 0.0031263873, -0.03244195, 0.015886668, -0.31585652, -0.055220343, -0.030137295, -0.0047442047, -0.024100104, -0.026151866, 0.009740438, 0.023495821, 0.019925868, 0.005912481, 0.058725912, -0.003270413, 0.04348882, 0.030009557, -0.0055912044, 0.019371249, -0.01072635, -0.0093974685, -0.008006356, -0.03293336, 0.065376535, -0.030116912, -0.0050215623, 0.02215724, 0.08487462, -0.01512167, 0.04139201, -0.039469626, 0.010686566, 0.0119911535, 0.027665704, 0.010860046, -0.0060399976, -0.02167751, 0.06864893, -0.06688245, -0.020013431, 0.052565284, 0.036595438, -0.017483344, 0.0015104264, -0.033319857, 0.031127846, -0.016559338, 0.03260179, -0.0017103137, -0.035969757, -0.0072414135, -0.023197405, 0.06881526, 0.03716938, 0.040767778, 0.008253217, 0.009972135, -0.011659296, -0.016925162, -0.024616797, -0.0051530204, -0.037713427, 0.0144299595, 0.027311156, -0.04369489, -0.029637577, -0.021351092, 0.011595228, -0.0077776928, -0.015793659, 0.0088956375, 0.07097735, 6.356993E-4, -0.07671601, -0.045666553, -0.032896306, 0.031702023, -0.03788758, 0.010253627, 0.024420895, 0.07730532, 0.034487303, 0.029535713, 0.0052707805, 0.033303913, 0.031802993, 0.024269108, 0.002916546, 0.060003944, 0.03327528, 0.039296333, 0.02154667, 0.039479017, 0.018419271, 0.0122833, 0.010676563, -0.048565764, -0.012351523, -0.063058205, 0.026472325, -0.043562215, 0.0059786336, 0.02926196, -0.05234941, 0.02095955, 0.01948741, 0.020490514, 0.039850615, -0.002022933, -0.07824235, -0.021833528, -0.01800028, -0.021009289, -0.029798916, -0.05278395, -0.029473618, 0.03768821, 0.014928071, -2.5071797E-4, 0.070851505, -0.012776307, 0.03642812, 0.05638633, -0.035331666, 0.022576703, -0.025339553, -0.01823377, 0.013824167, 0.014462281, 0.0077064047, 0.010565181, -0.010814993, 0.070219785, -0.0115902675, 0.0063769505, 0.039828464, -0.035489902, -0.06226308, -0.022480406, 0.028937314, -0.09581581, 0.044895776, 0.0138532, 0.033628974, -0.021258889, -0.02214923, 0.008623505, -0.015368985, 0.01652804, 0.0052264086, -0.0034629959, 0.03410006, 0.004225493, 0.06447294, -0.0015660097, -0.01840149, 0.041613027, -0.034647305, -0.041094832, -0.0076485625, -0.011548803, -0.008955937, 0.023915716, -0.05750845, 0.013571776, 0.038035564, 0.051214285, 0.017229619, 0.054310832, -0.040345266, 0.046705592, 0.01892023, -0.017139433, 0.024902249, 0.0075987945, -0.04778435, -0.023536516, 0.013777308, -0.012842362, -0.056541786, -0.010031047, -0.028869353, -0.020860467, -0.0289887, 0.005462599, -0.014276646, -0.042962793, -0.06643013, 0.033159018, 0.0574382, -0.010921852, -0.04220447, 0.031255085, 0.035901096, 0.0053611547, -0.03960842, 0.043997083, -0.034420036, -5.7138974E-4, 0.023594886, 0.003760798, 0.058932602, -0.020205019, -0.005331159, 0.009501557, -0.009174396, -0.005978469, -0.0116181355, 0.057797506, -0.08766269, -0.034556657, -0.0424041, 0.023948673, -0.027255371, 0.043171518, 0.019607179, -0.003564329, -0.0013386213, 0.06896394, -0.02836739, -0.0025727802, -3.5907567E-4, 0.002725034, -0.0056025833, 0.03396514, -0.06422825, -0.015791941, 0.04027637, 0.03748832, -0.012592282, 0.041586798, 0.034388766, 0.01842983, -0.0763847, 0.026048746, 0.020475041, -0.025982415, -0.08021721, 0.04300156, 0.012852337, 0.0050624884, 0.030164517, -0.016625091, -0.0203026, -0.03899613, 0.018693378, -0.031331427, -0.037620526, -0.027912112, 0.022231385, -0.021127658, 0.019727051, 0.019486453, 0.048075598, -0.038425423, -0.00397234, 0.028609352, 0.017644716, -0.058366902, -0.012867967, -0.021269372, -0.04848771, -0.031257644, -0.010948436, -0.005674635, 0.023258856, -0.012111394, 0.0011336876, -0.017391304, 0.36719078, -0.026885467, 0.060930785, 0.0044674836, -0.05804051, -0.010229996, -0.07351183, 0.03794624, -0.01075405, 0.03108142, -0.040177867, 0.0069739777, -0.0024739015, -0.029498614, 0.0068185064, 0.024373513, 0.006817893, -0.009616754, -0.044036273, -0.030814769, 0.023808507, 0.01749889, -0.013937924, -0.013928672, 0.0077683646, -0.07406683, 0.0023005882, 0.069199316, -0.019558819, -0.008927713, -0.03769704, 0.03683285, -0.034151502, -0.03660342, -0.009205413, 0.058331266, 0.02384014, -0.01883961, -0.001598962, -0.07191259, -0.024390854, 0.021434834, -0.040430058, 0.015317319, -0.057455387, 0.08343679, -0.029132226, -0.011998974, 0.032161973, -0.011554039, -0.008016847, 0.0020131513, -0.0041615823, -0.03961297, 0.051502813, 0.048388653, 0.091617, -0.013698825, -0.00415278, 0.01443872, -0.04094697, -0.05632768, 0.07789866, -0.019574445, 0.010072907, 0.014609338, -0.06608522, 0.10504081, -0.0857161, 0.029013494, 0.0032321974, -0.041201923, -0.0062367213, 0.054656375, 0.048450284, 0.035362236, -0.047136497, 0.015893556, -0.09251543, -0.006156136, 0.2748038, -0.021822594, -0.023961814, -0.041063424, -0.0044170385, 0.0064211693, -0.0030538451, -0.0196417, 6.976129E-5, -0.022948751, -0.0025305662, -0.022325622, 0.016686456, -0.001411661, 0.04078428, -0.046055574, 0.014063497, 0.008300389, -0.02120225, 0.10003629, -0.027692214, -0.029307956, 0.007577994, 0.026423063, -0.020059232, 0.023596935, 0.027013354, 0.034368098, -0.025882598, -0.03949743, -0.03740364, -0.047155123, -0.025286378, -0.029994665, -0.004557678, -0.027749574, 0.0023474477, -0.005861826, 0.0079605365, -0.16932198, 0.026209744, -0.036471505, 0.058631543, 0.016551282, 0.01946445, -0.038487468, 0.0061673815, -0.02962428, 0.03679862, -0.033935014, -0.04036175, 0.03572401, -0.018257549, -0.008237133, -0.0337758, -0.1909525, -0.051766858, -0.017688802, -0.007546954, 0.10857811, -0.036305413, 0.010601537, -0.013065671, 0.0041751885, -0.01093284, -0.0042866794, -0.024865638, 0.0019628413, -0.0036851282, -0.015139624]
`
"pokemen.jpeg"图像提取的特征向量：
`[0.04291167, -0.044843696, -0.03097795, -4.9871154E-4, -0.022471981, -0.021111676, 0.03564713, -0.027644252, 0.02879835, 0.030088553, -0.016895836, -0.06816551, -0.01816209, -0.046549335, 0.022306086, -0.00732047, -0.030832667, 0.017333077, 0.035218116, 0.013897745, -0.015995989, 0.036162, -0.011234188, 0.005423994, 0.010988035, 0.016934227, -0.027328221, 0.045175508, -0.0076799723, -0.008428099, 0.0379283, -0.014139321, 0.047218155, -0.0014213651, -0.018526262, -0.038786165, 0.009058541, -0.043532215, -0.082614265, 0.05132469, -0.002871491, -0.02540377, -0.0055608796, 0.042899515, -0.02526434, -0.008268931, 0.09919197, -0.014118161, 0.011939004, -0.0378673, -0.023684131, 0.0041754516, 0.018177506, 0.023189444, -0.03443699, -0.030539466, -0.016246956, 0.025662767, -0.014916782, -0.013212942, -0.0403162, -0.014053546, -3.4126997E-4, 0.029778289, -2.702353E-4, 0.0019313254, 0.008906599, 0.037928384, -0.012529874, -0.03187279, -0.01576191, 0.02401978, 0.041783296, 0.017492805, 0.032698546, -0.019135954, -0.007894231, 0.008195202, 0.019654706, -0.008588497, 0.0025250942, -4.4908558E-4, 0.012947083, -0.035057016, -0.029291084, -0.008478567, 0.00871798, -0.005650729, 0.03245429, 0.01756112, 0.005083982, 0.013908106, 0.004997189, 0.007285399, 0.030292885, 0.010426409, -0.011307953, -0.021766523, 0.016702566, 0.017671512, 0.040448118, 0.013628815, 0.012100159, -0.1914912, -0.02235963, -0.0077098273, 0.029523864, 0.0060935, 0.021086408, 0.019624252, -0.007848345, 0.024103342, 0.031233579, 0.06333284, -0.03386657, -0.015521895, 0.040551715, 0.002229173, -0.051189322, -0.019326886, 0.051572364, 0.039873846, -0.011595189, 0.021191852, 0.08176732, 0.018292895, 0.116725475, 0.046153095, 0.02112811, -0.005026102, 0.035785478, 9.714082E-5, -0.026679788, 0.028267741, 0.034072038, -0.017276939, -0.010419982, 0.0068608276, 0.013247849, 0.03677897, -0.008979279, -0.054101545, -0.014908809, 0.008746554, -0.034527823, -0.034220256, 0.010058826, -0.038417008, 0.003455152, 0.01719288, 0.011936971, 0.016658563, 0.022657398, 0.018386025, -0.03173304, -0.03093923, 0.010592256, 0.017440747, 0.026558653, -0.03289368, 0.053077318, -0.0032798748, -1.8944877E-4, -0.010116159, 0.0049398644, 0.028703315, 0.011148799, -0.060408156, 0.037205603, -0.017390653, -0.014094147, -0.029708443, 0.029247316, -0.008445463, -0.027834352, 0.015934266, -0.020664394, 0.042258333, 0.10022003, 0.039152957, 0.04105683, 0.0026882456, -0.02522875, 1.9583324E-4, -0.012959812, -0.0137978215, 0.017290823, -0.03030226, -0.028914176, 0.006328738, -0.024444595, -0.035492763, 0.0073898523, -0.019974006, 0.002685098, -0.027104482, -0.06936217, -0.038497116, -0.027177377, 0.045475744, 0.012367801, 0.0116779655, 0.027815234, -0.07771035, -0.032675862, 0.015993595, -0.012342518, -0.010706397, -0.05750869, -0.0011569815, 0.018698452, 0.003930302, -0.024890527, -0.028365264, -0.032367073, 0.020655649, -0.0038955747, 0.020181242, -0.011517744, -0.033087634, -0.027701976, -0.0037072022, 0.005043209, 0.0064629805, -0.00524952, 0.051886875, -3.8694925E-4, 0.02261193, -0.0037769252, 0.012613308, 0.020934463, -0.015333431, -0.01825341, 0.004195353, 0.020285629, 0.0396503, -0.0030241467, -0.003163454, 0.032337684, -0.0071487934, -0.046873227, -0.0237406, 0.030143345, -0.0028347333, 0.059865776, 0.03338275, 0.031473532, -0.02145327, 0.052916422, -0.022935554, 0.011062363, -0.12641339, -0.012136323, -0.018136695, 0.08574332, 0.024156999, -0.024803355, 0.053983577, 0.046291098, -0.018676125, 0.06142258, 0.015752105, -0.02157057, 0.0066583036, -0.018354656, -0.00169666, 0.042754065, 0.024247173, 0.0040707747, 0.028440328, 0.017933236, 0.0045022396, -0.035256848, 0.031215727, -0.064471304, -0.020558588, 0.02226645, 0.018865466, 0.0029210933, 0.03285621, -0.04002781, 0.006461194, 0.016687267, 0.06702747, -0.010025386, 0.009313614, -0.0056495615, -0.011187735, -0.008945216, -0.0086424295, 0.010674934, -0.015839532, -0.008439096, -0.033949062, 0.032860823, -0.010637974, -0.030248038, 0.04869478, -0.061749846, -0.006122953, -0.03129915, 0.02523003, 0.02518741, -0.039217878, -0.0024310295, -0.027349027, -0.0019470695, -0.010807605, 0.0053634346, -0.022171726, 0.01585149, 0.015705466, -0.060566317, -0.056944314, -0.02116855, -0.036960077, -0.0022319832, -0.014876733, 0.044293076, -0.05829122, -0.008812449, 0.030809397, 0.0054350267, 0.0145844575, 0.0077701006, -0.0018926729, 0.018474035, -0.042180866, -0.027280876, 0.014323922, -0.042439632, -0.005805423, -0.02021746, 0.0052913683, 0.033170614, -0.010268064, -0.025065895, -0.025387438, 0.018491995, 0.0019102496, -0.009523303, -0.015760522, 0.018927813, -0.029335143, 0.0014734012, 0.0074662496, -0.044093568, -0.0059505682, -0.023221957, -0.036290392, 0.06524591, -0.00947147, -0.021093009, 0.014719667, 0.0028312954, -0.042829204, -0.0027476442, -0.026514305, -0.00758794, -0.0046956497, 0.013879978, -0.027092524, 0.150382, 0.0023151883, 0.02776736, 0.0095762005, -0.03874025, 0.037726372, -0.0086296, 0.025609106, 0.020442897, 0.016689777, 0.016329788, 0.08118079, 0.0028079955, 0.002607449, -0.016306203, -0.043958742, 0.0089164665, -1.5896777E-4, -0.019521944, -0.050880868, 0.20863998, -0.019641802, -0.0019702485, 0.009458314, -0.0119787585, 0.009010635, 0.0067173513, 0.06730034, 0.07060136, 0.014370495, 0.031192722, 0.025965312, -0.13825452, -0.0047878004, 0.0031418095, 0.051346373, 0.03473993, -0.027437951, 0.017205695, -0.045061916, -0.031983115, 0.008098407, 0.048467815, 0.02006455, -0.03776604, 0.0118782995, 0.0053039393, 0.013879072, -0.03031766, -0.00915758, 0.0072234436, -0.016118713, 0.038302325, -0.022366343, 0.021374855, 0.021396242, 0.015607489, 0.029557128, 0.009377498, -0.01485313, -0.019354194, 0.029676395, -0.0027675244, -0.012943141, -0.034268502, -0.01057757, -0.014670935, 0.09091737, -0.009547132, 3.3995404E-4, -0.0136253415, 0.008343481, -0.025839072, 0.0537884, 1.6418177E-4, 0.011854879, -0.035404906, -0.018872093, -0.04182076, 0.029936738, 0.64360344, -0.012127994, -1.4851912E-4, -0.03552247, 0.005601581, -0.01674788, 0.014529066, 0.033003937, -0.024850665, -0.017618157, 0.014206154, -6.743941E-4, -0.015137939, -0.02261175, 0.009758324, 0.0175693, 0.02857591, -0.0069276174, 0.009783207, -0.019306893, 0.014744373, -0.046966605, -0.012184104, -0.043031886, 0.0035463425, 0.095387146, 0.0066176103, -0.0012541268, 0.0064918925, -0.04874745, 0.026564501, 2.0008913E-4, 0.034782503, -0.040478807, 0.03309725, 0.025427176, 0.047073677, -0.0038363202, 0.015069002, -0.08724451, 0.008610659, -0.03316835, -0.001608728, 0.03467253, 0.018248443, -7.048728E-4, -0.008348238, -0.014957135, -0.009729947, 0.05856529, -0.019249208, 0.008126142, 0.0035701196, 0.021702213, -0.011999915, -0.09011504, -0.0039964197, -0.0100608785, 0.014382758, -0.036305144, -0.05058678, -0.023472827, -0.02383653, 0.07436498, 0.028283553, 0.0036904947, 0.0059109894, -1.9413815E-4, 0.007912339, 0.004024776]
`

**Comment by zhangjh** [comment]
已经解决了，逐步对比了每个关键步骤的输出，已经查看了torchvision对应图片预处理函数的实现源码，发现是在图片预处理阶段ToTensor过程中，java实现的逻辑和torchvision的不一样。
这里python的实现图片对应的模式顺序是CHW，而java下默认使用的是HWC。。。
核心代码：
```java
        INDArray imageDataCHW = imageDataHWC.permute(2, 0, 1);
```
调整了代码实现后输出结果符合预期了。

**Comment by Young-Flash** [comment]
@zhangjh 想请教大佬一个问题，在 Python 侧计算文本向量的步骤是先使用 text = clip.tokenize(...) 进行预处理然后再将得到的结果送入 model.encode_text(text)，那么对应到安卓中是如何进行 text = clip.tokenize(...) 这一步的呢？

**Comment by zhangjh** [comment]
> @zhangjh 想请教大佬一个问题，在 Python 侧计算文本向量的步骤是先使用 text = clip.tokenize(...) 进行预处理然后再将得到的结果送入 model.encode_text(text)，那么对应到安卓中是如何进行 text = clip.tokenize(...) 这一步的呢？

类似的，需要将clip的Tokenize实现用Java转写然后再调用
```
Tokenization.FullTokenizer tokenizer =
                new Tokenization.FullTokenizer(context, true);
        List<String> tokens = tokenizer.tokenize(text);
```
转写的代码我传了一份，可以看这里：https://gist.github.com/zhangjh/34a8637fb03ae7350b661e54b67b7170

**Comment by Young-Flash** [comment]
> > @zhangjh 想请教大佬一个问题，在 Python 侧计算文本向量的步骤是先使用 text = clip.tokenize(...) 进行预处理然后再将得到的结果送入 model.encode_text(text)，那么对应到安卓中是如何进行 text = clip.tokenize(...) 这一步的呢？
> 
> 类似的，需要将clip的Tokenize实现用Java转写然后再调用
> 
> ```
> Tokenization.FullTokenizer tokenizer =
>                 new Tokenization.FullTokenizer(context, true);
>         List<String> tokens = tokenizer.tokenize(text);
> ```
> 
> 转写的代码我传了一份，可以看这里：https://gist.github.com/zhangjh/34a8637fb03ae7350b661e54b67b7170

@zhangjh 感谢大佬。大佬能另外再分享一下图片的预处理吗？我也遇到了图片内存布局排列的问题，尝试了各个维度的 permute 都不能和 Python 端的图片向量一致

**Comment by zhangjh** [comment]
> > > @zhangjh 想请教大佬一个问题，在 Python 侧计算文本向量的步骤是先使用 text = clip.tokenize(...) 进行预处理然后再将得到的结果送入 model.encode_text(text)，那么对应到安卓中是如何进行 text = clip.tokenize(...) 这一步的呢？
> > 
> > 
> > 类似的，需要将clip的Tokenize实现用Java转写然后再调用
> > ```
> > Tokenization.FullTokenizer tokenizer =
> >                 new Tokenization.FullTokenizer(context, true);
> >         List<String> tokens = tokenizer.tokenize(text);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 转写的代码我传了一份，可以看这里：https://gist.github.com/zhangjh/34a8637fb03ae7350b661e54b67b7170
> 
> @zhangjh 感谢大佬。大佬能另外再分享一下图片的预处理吗？我也遇到了图片内存布局排列的问题，尝试了各个维度的 permute 都不能和 Python 端的图片向量 `image = preprocess(Image.open("image.jpg")).unsqueeze(0).to(device)` 一致

预处理就是resize，toRgb，没有什么。要注意的就是上面提到的图片模式问题，torchvision的处理顺序是chw，java的库默认是hwc，需要调整一下

**Comment by gg159753** [comment]
@zhangjh 大佬厚着脸皮问一下   我太菜了  预处理这部分实现不太会  能不能给一份文本处理的完整的示例

**Comment by zhangjh** [comment]
> @zhangjh 大佬厚着脸皮问一下 我太菜了 预处理这部分实现不太会 能不能给一份文本处理的完整的示例

1. resize
```
private Bitmap resizeImage(Bitmap image) {
        float scaleWidth = ((float) 224) / image.getWidth();
        float scaleHeight = ((float) 224) / image.getHeight();
        Matrix matrix = new Matrix();
        matrix.postScale(scaleWidth, scaleHeight);
        return Bitmap.createBitmap(image, 0, 0, image.getWidth(), image.getHeight(), matrix, true);
    }
```
2. toRgb
```
private Bitmap convertToRGB(Bitmap image) {
        Bitmap rgbImage = Bitmap.createBitmap(image.getWidth(), image.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(rgbImage);
        canvas.drawBitmap(image, 0, 0, null);
        return rgbImage;
    }
```

**Comment by lee88688** [comment]
@zhangjh 请问一下您那边部署的时候有做量化吗？尝试了以下量化onnx导出的f32模型，有点问题。

**Comment by zhangjh** [comment]
> @zhangjh 请问一下您那边部署的时候有做量化吗？尝试了以下量化onnx导出的f32模型，有点问题。

看你应用场景，我是手机端运行，我量化了的。
可以看下我这篇介绍文档：https://github.com/zhangjh/SmartSearch_doc

**Comment by sineom-1** [comment]
大佬，请教下量化的问题，目前导出了ONNX的模型，量化为FP16的在移动端无法使用，FP32的模型又太大了，卡在这儿不知道怎么处理了，可以麻烦大佬指定下量化的方面么？

**Comment by lee88688** [comment]
> 大佬，请教下量化的问题，目前导出了ONNX的模型，量化为FP16的在移动端无法使用，FP32的模型又太大了，卡在这儿不知道怎么处理了，可以麻烦大佬指定下量化的方面么？

量化成int8才能在移动端比较好的运行，我做了一些尝试，可以参考一下[我项目中的notebook](https://github.com/lee88688/Chinese-CLIP/blob/generate-onnx/onnx.ipynb)

**Comment by sineom-1** [comment]
> > 大佬，请教下量化的问题，目前导出了ONNX的模型，量化为FP16的在移动端无法使用，FP32的模型又太大了，卡在这儿不知道怎么处理了，可以麻烦大佬指定下量化的方面么？
> 
> 量化成int8才能在移动端比较好的运行，我做了一些尝试，可以参考一下[我项目中的notebook](https://github.com/lee88688/Chinese-CLIP/blob/generate-onnx/onnx.ipynb)

感谢大佬
