### ISSUE TITLE
请问您整理的用来预训练模型的大规模中文数据（~2亿的图文对数据）公开吗？

### ISSUE THREAD

**Issue by huhuhuqia** [OFA-Sys/Chinese-CLIP#133]
请问您整理的用来预训练模型的大规模中文数据（~2亿的图文对数据）公开了吗？

**Comment by yangapku** [comment]
您好，我们这份工作预训练使用的数据集，尽量都选择了大家可以公开获取收集的数据。具体细节可以参见我们的[技术报告paper](https://arxiv.org/pdf/2211.01335.pdf)。我们预训练使用的数据，主要由LAION-5B中的中文部分 + wukong中文图文数据集 + 很少量英文公开学术数据集构成，这些都是我们直接使用的其他研究者已经开源的数据，可以从公开渠道获取下载的。此外加入了少量内部从图虫网抓取的图片，因为属于公司内部抓取的业务数据，所以直接分享会有一些问题，您可以自己考虑抓取或者购买哈。总体来看，因为这部分数据量级还是较小，影响也不会特别大，整体还是LAION数据主导。

如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！
