### ISSUE TITLE
如何将cn-clip集成到open_clip中？

### ISSUE THREAD

**Issue by Adenialzz** [OFA-Sys/Chinese-CLIP#137]
您好，非常感谢您开源中文clip模型。请问如何将cn-clip的模型集成到open_clip中？
我自己做了一些尝试，可以正常下载hf的cn-clip权重并加载，但目前在模型config配置上出现一些问题。注意到您提到cn-clip是基于open_clip实现的，那么是否能够通过添加一个config文件（如[ViT-B-16](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/model_configs/ViT-B-16.json)）的方式，将cn-clip继承到open_clip中，使得open_clip可以加载cn-clip的权重进行测试呢？
期待您的回答。

**Comment by yangapku** [comment]
您好，这里主要的问题是我们的文本侧结构和原始的CLIP不同，所以这里无法直接做到代码兼容哈。图像侧部分的代码，我们直接是从open_clip沿袭来的，所以是ok的。

**Comment by yangapku** [comment]
我们的代码是基于open_clip比较早期的版本开发的哈，基本使用方法是一致的。如果您有一些open_clip的新特性，需要我们这边cn-clip的代码库兼容，也可以提出您的需求哈，我们会看看能否安排同学进行适配。

**Comment by Adenialzz** [comment]
好的，明白，我这边自己封装了一下在用了。感谢回复

**Comment by RyanYip-Kat** [comment]
@Adenialzz 请问您能分享下吗？我刚好也在做这个现在

**Comment by Adenialzz** [comment]
我目前只是封装了一下cn-clip的接口，没有在open_clip中直接集成cn-clip的文本侧模型结构。
