### ISSUE TITLE
load_from_name加载本地模型需要其他操作吗？

### ISSUE THREAD

**Issue by Bothgone** [OFA-Sys/Chinese-CLIP#138]
如题，如果使用load_from_name加载本地模型，除了需要额外输入对应的vision_model_name，text_model_name，以及input_resolution,是否需要修改其他文件？如果我的模型与预训练模型有出入，需要我做什么操作吗？

**Comment by DtYXs** [comment]
您好，在使用`load_from_name`加载本地模型时，输入的`vision_model_name`和`text_model_name`的config文件需要在`cn_clip/clip/model_configs`目录下存在，其中不同规模的Chinese-CLIP模型对应的config文件已经默认在该目录下了。如果是您自定义的模型，可能您需要自行设置对应的config文件。
