### ISSUE TITLE
训练时损失一直不降，这种情况怎么样处理呢？

### ISSUE THREAD

**Issue by Duyz232** [OFA-Sys/Chinese-CLIP#142]
以下是我训练用的脚本：
<img width="565" alt="5c0cef5b37035b54e4d89836ced1c79" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/110820271/e8f36149-8183-4542-8d94-ceab87d6222c">
<img width="521" alt="450b557adf006c6f7a41d32e818232c" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/110820271/a4ed7824-1c02-4478-8d68-ebaa118943d5">
训练时候损失一直不降:

<img width="754" alt="360dbc34a37276e853d9764cfc5d196" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/110820271/6a457f27-0ead-4511-a4d7-6c13823342d3">

**Comment by DtYXs** [comment]
您好，由于您的batchsize设置较小，因此几个step可能loss的变化并不会特别明显。
建议您首先对比一下目前的loss和刚开始训练时的loss，如果在逐渐降低则说明模型应该是在正常收敛的，您可以再多观察一段时间看看loss的变化。
您也可以尝试适当增大一些学习率，同时可以参考[模型finetune](https://github.com/OFA-Sys/Chinese-CLIP/issues/142)部分的说明，尝试加入`--grad-checkpointing`参数来启用重计算策略等方式来减少显存占用，进而设置更大的batchsize。

**Comment by Duyz232** [comment]
您好，非常感谢您的回复。
一开始我是打算从头开始训练，checkpoints被我注释掉了。我后面会采取您的建议，加载已经练好的checkpoints，进行微调


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月19日(星期一) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] 训练时损失一直不降，这种情况怎么样处理呢？ (Issue #142)





 
@Duyz232 检查一下你的checkout 是否加载成功，的sh在默写环境下，环境变量是失效的，需要你把相对路径修改为绝对路径，我先前也遇到过这样的问题，检查了初始化就没问题了
