### ISSUE TITLE
可以给bert tokenizer添加自己额外的词汇吗

### ISSUE THREAD

**Issue by dandyxxxx** [OFA-Sys/Chinese-CLIP#144]
cn_clip这个库的bert我还没找到怎么操作给bert tokenizer添加自己额外的词汇，请教一下各位

**Comment by yangapku** [comment]
您好，这个操作会比较复杂了，您可以调研下中文bert是否有增加定制词汇的做法，我们其实应该和典型的中文bert是一致的。

**Comment by yangapku** [comment]
可以考虑利用bert词表文件中几个[unused] token哈。

**Comment by dandyxxxx** [comment]
> 可以考虑利用bert词表文件中几个[unused] token哈。

非常感谢，这个方法可以
