### ISSUE TITLE
请问怎么在已经预训练好的base模型上，基于自己的图文数据继续做图文预训练？

### ISSUE THREAD

**Issue by sudazzk** [OFA-Sys/Chinese-CLIP#145]

**Comment by yangapku** [comment]
您好，建议您先上手下我们提供的示例notebook，在电商下游数据集上试试，我们提供了非常详细的手把手教学哈。

**Comment by sudazzk** [comment]
3Q

**Comment by sudazzk** [comment]
追问一下，基于自己微调后的模型怎么转成huggingface上的模型格式？

**Comment by sudazzk** [comment]
在 https://github.com/OFA-Sys/Chinese-CLIP/issues/48 里看到了~~~
