### ISSUE TITLE
模型测试

### ISSUE THREAD

**Issue by Duyz232** [OFA-Sys/Chinese-CLIP#147]
如何测试自己微调后的权重？我尝试用如下脚本检测自己微调后的权重：
![499828e12d8ea738a287a7c4ad99fc7](https://github.com/OFA-Sys/Chinese-CLIP/assets/110820271/20d4ef9d-7667-400b-82e7-b68c2c450d2c)
但是存在如下报错：
![525ab9909074283f95068517e95feb3](https://github.com/OFA-Sys/Chinese-CLIP/assets/110820271/8579a039-9144-48c9-9bf8-d5c0e2780e28)
这种情况我该如何解决呢

**Comment by DtYXs** [comment]
您好，判断您可能是想加载本地自己训练好的模型，应该使用[API快速上手部分](https://github.com/OFA-Sys/Chinese-CLIP#api%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)中的`load_from_name`函数，您可以参考https://github.com/OFA-Sys/Chinese-CLIP/issues/63#issuecomment-1443551937 中的回答。
