### ISSUE TITLE
finetune的时候，原始的clip_cn_vit-b-16.pt只有700M，但是checkpoint 却有2G？

### ISSUE THREAD

**Issue by Rainyfish** [OFA-Sys/Chinese-CLIP#149]
resume的模型是clip_cn_vit-b-16.pt
vision model选择的是vit-b-16
text model 选择的是：RoBERTa-wwm-ext-base-chinese
这种配置是
<img width="740" alt="1687836083003" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/27812031/83f1c21d-21fa-4a6e-90cc-95e61d0cc37c">
相同的
为什么模型会有不同呢

**Comment by xuboot** [comment]
我微调一条数据测试也是，
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/54123895/a647bf6a-7278-42c2-9d35-777defb44089)
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/54123895/dc8088e6-3dd1-4641-856a-837f21724501)

**Comment by yangapku** [comment]
这个是正常的，因为我们提供的ckpt文件去掉了预训练过程中的optimizer state，而您自己微调的模型会把训练中的optimizer state存下来，用于中断的情况下接续训练。如果用torch.load读取这些文件，会发现里面差optimizer这部分。

**Comment by Rainyfish** [comment]
@yangapku 那如何去除模型里面的optimizer呢？直接torch.load,然后save?

**Comment by yangapku** [comment]
是的哈，load之后是一个python dict，删去optimizer所在的key，再save，就可以了哈。

**Comment by xuboot** [comment]
@yangapku 怎么改，大佬

**Comment by yangapku** [comment]
@xuboot 您好，很简单哈：
```python
import torch
model_state = torch.load("model_path") # 指定输入ckpt路径
print(type(model_state)) # python dict
del model_state['state_dict']
torch.save(model_state, "output_path") # 指定输出ckpt路径
```
