### ISSUE TITLE
CN-CLIPViT-B/16 模型在Flickr30K-CN数据集上的zero-shot结果复现不出来

### ISSUE THREAD

**Issue by ddNTP** [OFA-Sys/Chinese-CLIP#15]
你好，我使用你们开源的CN-CLIPViT-B/16 模型在MUGE上复现的结果和你们汇报的结果差不多
![image](https://user-images.githubusercontent.com/52226902/202694566-4ae406a3-9a36-4ad5-b44f-1f263ed57fb6.png)

但是在Flickr30K-CN数据集上的结果差很远，不知道问题出在哪里，麻烦帮忙看下，谢谢。
![image](https://user-images.githubusercontent.com/52226902/202695129-a8d291e4-ebdb-452d-bbe0-dd3ae668d98b.png)

**Comment by ddNTP** [comment]
![image](https://user-images.githubusercontent.com/52226902/202703081-94b2d0d3-dd80-4988-bef8-dfed45c5616c.png)
在Flickr30K-CN数据集上，不管是zero-shot还是finetune，结果都差很多。

**Comment by yangapku** [comment]
另外您可以先主要关注zero-shot的对齐，这个因为不涉及训练的超参配置，应该是和我们汇报结果基本不会有效果差别的。关于finetune的最优超参，我们技术报告的附录中，给出了finetune复现结果的每组实验的超参配置，主要是batchsize需要开得比较大，供您参考。

**Comment by ddNTP** [comment]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/52226902/202846888-82e92a2b-6359-47a0-8df7-eb0a784c53e2.png">
您好,我图文特征提取使用的context_length设为52之后，zero-shot的结果还是普遍差一些，不知道还有什么地方出现问题了？

**Comment by yangapku** [comment]
您好，我看到这次结果差距相对小很多了，您可以再试试换成我们在readme中已经提供好的预处理过的Flickr30K-CN数据，看看结果如何

**Comment by ddNTP** [comment]
事实上，我用的是你们提供的Flickr30K-CN数据测试集测的，另外你们提供的数据形式用的是query_id，query_text，item_ids
<img width="722" alt="image" src="https://user-images.githubusercontent.com/52226902/202848190-cb90fab7-8a89-449b-9ac7-dd3f4da40e41.png">
我转换成你们默认需求的格式测的
<img width="724" alt="image" src="https://user-images.githubusercontent.com/52226902/202848254-8ac7cd2d-dd30-4b93-aa9a-2a04222534a5.png">

**Comment by yangapku** [comment]
明白，字段名字这个可能是我们数据集准备时候的问题，后面我们按要求的字段名更正过来。您方便提供下运行环境的python包信息吗？尤其是torchvision和pytorch的版本，我们也可以去复现看看。

**Comment by ddNTP** [comment]
torch  1.8.0
torchvision   0.9.0
Python 3.7.10
cuda 10.2

**Comment by yangapku** [comment]
好的，我们也去复现一下

**Comment by yangapku** [comment]
> torch 1.8.0 torchvision 0.9.0 Python 3.7.10 cuda 10.2

您好，首先我们已经把字段信息更正好了，链接已经更新，您可以重新下载下。用这版数据，我们找了一台新机器，配好了您所指定的环境，结果和我们的报告结果基本一致了（IR R@1/5/10 62.7/86.8/92.8, TR R@1/5/10 74.6/93.5/97.1, 考虑到机器和环境差异可能和论文会有个±0.1的指标误差），您也可以再走一遍流程，应该没有问题的。

**Comment by ddNTP** [comment]
您好，我在v100上测试结果没变，还是之前的结果，
用a100测的结果略微降低
![image](https://user-images.githubusercontent.com/52226902/203962543-ba7f2aad-9775-47b9-9bd8-e45af285ee97.png)

**Comment by yangapku** [comment]
@ddNTP 您使用了我们最新上传的Flickr30K-CN处理好的数据包吗？可以试试哈

**Comment by yangapku** [comment]
@ddNTP 用最新的数据包，和您提供的环境版本，我们在A100上面直接运行开源推理和评测代码，实测结果为IR R@1/5/10 62.7/86.8/92.8, TR R@1/5/10 74.6/93.5/97.1哈，所以建议您用最新的数据包再看下。之前的数据包，图片base64可能是我们比较早先的预处理流程产出的，我们这次检查并对齐到了我们实际论文实验使用的数据版本哈

**Comment by ddNTP** [comment]
我刚刚使用了你们最新上传的Flickr30K-CN数据集在v100和a100上测试了zero-shot结果，结果和之前没有任何变化。能麻烦你们自己下载一下你们开源的CN-CLIPViT-B/16 模型的和Flickr30K-CN数据集，用这个开源推理和评测代码测试一次吗？可能有地方没有对齐，谢谢

**Comment by yangapku** [comment]
> 我刚刚使用了你们最新上传的Flickr30K-CN数据集在v100和a100上测试了zero-shot结果，结果和之前没有任何变化。能麻烦你们自己下载一下你们开源的CN-CLIPViT-B/16 模型的和Flickr30K-CN数据集，用这个开源推理和评测代码测试一次吗？可能有地方没有对齐，谢谢

@ddNTP 上面回复您的结果，就是我们找了一台新机器，拉取最新的开源代码、数据集和base模型，使用readme的示例推理和评测代码跑出来的，并且我们有两个同学各跑了一次都是这个IR R@1/5/10 62.7/86.8/92.8, TR R@1/5/10 74.6/93.5/97.1结果。稍后我把我们连同配环境，整个在机器上运行的command history和输出打个log发出来，供您参考。

**Comment by yangapku** [comment]
@ddNTP 您好，下面两个链接，分别是我们在一台新的V100机器上，配环境过程的log、以及拉取开源资源（代码+ckpt+数据）并进行评测的log：
https://clip-cn-beijing.oss-cn-beijing.aliyuncs.com/others/flickr30k_cn_set_environment.log

**Comment by ddNTP** [comment]
我测了一次CN-CLIPViT-H/14，结果和汇报的差不多。CN-CLIPViT-B/16还是原来的结果，不过差的也不大，至少比最开始差距小多了，这个问题就到这吧，感谢您的热情回复:)
