### ISSUE TITLE
求一份COCO-CN数据集

### ISSUE THREAD

**Issue by czczup** [OFA-Sys/Chinese-CLIP#152]
大佬们下午好。在COCO-CN的原作者那里填写了数据申请表单，但没有收到回复。能否分享一份COCO-CN数据集，只要有文件名和标注的txt文件就行，我的邮箱是czcz94cz@gmail.com。感谢！

**Comment by yangapku** [comment]
您好，还是请您先得到原作者通过，然后截个图给到我们哈，我们会很快提供的。如果没有原作者的许可，我们直接提供会有一些风险哈，这是违背原作者要求的。
