### ISSUE TITLE
训练脚本卡在warning

### ISSUE THREAD

**Issue by Zoe-TAN** [OFA-Sys/Chinese-CLIP#153]
您好，我尝试在linux系统上进行训练，但是每到开头的warning就会卡住：

> /home/shuangyitan/.conda/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

> warnings.warn(

请问这是什么问题呢？谢谢！

**Comment by Zoe-TAN** [comment]
为单卡训练，

> > # Number of GPUs per GPU worker
> GPUS_PER_NODE=1 
> # Number of GPU workers, for single-worker training, please set to 1
> WORKER_CNT=1

**Comment by yangapku** [comment]
您好，请问方面提供一下您完整运行的脚本和运行环境（系统、python、cuda、pytorch版本）吗？我们考虑复现一下哈

**Comment by Zoe-TAN** [comment]
> 

你好，已经解决了，发现是机器IP输入错误的问题，非常感谢！
