### ISSUE TITLE
关于使用韩语roberta文本模型训练的问题

### ISSUE THREAD

**Issue by data-ant** [OFA-Sys/Chinese-CLIP#158]
**非常感谢您团队的杰出工作，谢谢！** 
**我想基于您的工作，训练一个基于韩语语言模型的CLIP模型，使用的韩语模型是klue/roberta-base
(https://huggingface.co/klue/roberta-base)
目前在训练时，出现了training loss不下降的问题，修改batchsize和lr都不起作用。想请教您应该如何解决？**
环境：
Python 3.7.10
torch：1.13.1+cu117
transformers：4.30.2

我具体是这样做的：
1.去掉--resume的同时，分别设置--clip-weight-path和--bert-weight-path
--clip-weight-path采用您提供的视觉模型:ViT-B-16.state_dict.pt
--bert-weight-path采用klue/bert-base提供的模型pytorch_model.bin

2.因为没有找到klue具体的模型代码，所以在使用时:
将cn_clip/clip/model.py中CLIP class中的
from cn_clip.clip.modeling_bert import BertModel#, KLUE_BertModel
self.bert = BertModel(self.KLUE_bert_config)
直接替换为：
from transformers import AutoModel, AutoTokenizer
self.bert = AutoModel.from_pretrained("*/pretrained_weights/KLUE/roberta-base")

3.训练遇到"module.bert.pooler.dense.weight"和 “module.bert.pooler.dense.bias”不参与计算loss，没有梯度的问题，将cn_clip/training/main.py 中的 find_unused_parameters设置为true

**Comment by DtYXs** [comment]
您好，根据描述您是想要打算在韩文数据上重新pretrain。由于这种情况下视觉模型和文本模型还没有对齐，因此一般loss会下降比较慢，通常需要较多的训练资源和时间，可以参考我们的[技术报告](https://arxiv.org/pdf/2211.01335.pdf)。

**Comment by data-ant** [comment]
我已收到，谢谢。
                      祝您诸事顺利!
