### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at 

### ISSUE THREAD

**Issue by l1771250640** [OFA-Sys/Chinese-CLIP#159]
作业报两种错误，第一种属于内存不足的问题
RuntimeError: cuda runtime error (2) : out of memory at /workspace/artifacts/paipytorch1.8/dist/ubuntu18.04-py3.6-cuda10.1/build/src/aten/src/THC/THCCachingHostAllocator.cpp:301
如下图所示
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/20339232/310cf255-bd97-4342-9866-afff1734df43)
日志链接为：https://logview.alibaba-inc.com/logview/?h=http://service.odps.aliyun-inc.com/api&p=cbu_irecom&i=20230711041431241gh3t8p7c8oy5_7aae42ed_c78a_4ee1_96c6_32f2e1002c67&token=QlhRMHNmM01vSE5EY2E4OXo0blB4dUZQOVJ3PSxPRFBTX09CTzoxMjU3NDcwMjYwNjk2OTQ4LDE2OTE2NDA4NzMseyJTdGF0ZW1lbnQiOlt7IkFjdGlvbiI6WyJvZHBzOlJlYWQiXSwiRWZmZWN0IjoiQWxsb3ciLCJSZXNvdXJjZSI6WyJhY3M6b2RwczoqOnByb2plY3RzL2NidV9pcmVjb20vaW5zdGFuY2VzLzIwMjMwNzExMDQxNDMxMjQxZ2gzdDhwN2M4b3k1XzdhYWU0MmVkX2M3OGFfNGVlMV85NmM2XzMyZjJlMTAwMmM2NyJdfV0sIlZlcnNpb24iOiIxIn0=

第二种 日志链接为
https://logview.alibaba-inc.com/logview/?h=http://service.odps.aliyun-inc.com/api&p=cbu_irecom&i=20230711054239599gdfvk5wb8oy5_00c403f6_faa7_49a6_8c1b_cd3ac298427b&token=cHBkMjY5dWZxa0FvejVsYW5nZms5SnNjbko4PSxPRFBTX09CTzoxMjU3NDcwMjYwNjk2OTQ4LDE2OTE2NDYxNjEseyJTdGF0ZW1lbnQiOlt7IkFjdGlvbiI6WyJvZHBzOlJlYWQiXSwiRWZmZWN0IjoiQWxsb3ciLCJSZXNvdXJjZSI6WyJhY3M6b2RwczoqOnByb2plY3RzL2NidV9pcmVjb20vaW5zdGFuY2VzLzIwMjMwNzExMDU0MjM5NTk5Z2Rmdms1d2I4b3k1XzAwYzQwM2Y2X2ZhYTdfNDlhNl84YzFiX2NkM2FjMjk4NDI3YiJdfV0sIlZlcnNpb24iOiIxIn0=
如下图所示：
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/20339232/2413843c-b1bb-4db9-a8ac-5fd6b8f66655)

反复重跑作业报这两种错误，第一种无论调大参数还是DworkerMemory还是调小batch-size均不管用。
第二种不清楚是什么原因，请看下~

**Comment by yangapku** [comment]
您好，看到您是阿里内部用户哈，您可以阿里钉和我（杨安）联系，避免数据安全问题~

**Comment by l1771250640** [comment]
好的，谢谢，因为不知道怎么联系，这里贴了链接。

**Comment by l1771250640** [comment]
嗯嗯，谢谢~
