### ISSUE TITLE
Imagenet zero shot results 

### ISSUE THREAD

**Issue by rom1504** [OFA-Sys/Chinese-CLIP#16]
Thanks for sharing these models and results for Chinese. Multilingual clips are important!

I see you have evaluation code for imagenet with Chinese prompts. Do you have results of your Chinese clip on imagenet with Chinese prompts and classnames?

**Comment by JustinLin610** [comment]
Not tested yet, as we still have some probles with the translation. We just test the models on Image Classification in the Wild, and will release the processed datasets and scripts soon.

**Comment by JustinLin610** [comment]
Hi, I just updated the results on ImageNe. Check [this](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/Results.md).

**Comment by rom1504** [comment]
great, thanks!

here's my result on multilingual fyi <https://github.com/mlfoundations/open_clip#vit-h14-xlm-roberta-large>

55.7% in chinese  so that's between your L/14 and your H/14

**Comment by rom1504** [comment]
I'm curious if combining mse between captions of 2 language and contrastive with image during training might help close the gap with english imagenet results
