### ISSUE TITLE
fine-tuning 后模型尺寸 2.3G

### ISSUE THREAD

**Issue by zengtao1978** [OFA-Sys/Chinese-CLIP#160]
在Flickr30k-CN数据集下，基于vit-b-16模型进行fine-tuning后，model尺寸膨胀到2.3G，这种尺寸，属于正常现象么？
如何缩小模型的尺寸？能够进行量化或蒸馏来减少模型尺寸么？

**Comment by yangapku** [comment]
您好，请您参见issue #149 哈，主要是因为训练后的ckpt增加了optimizer state，这个是可以手动清除掉的哈。

**Comment by zengtao1978** [comment]
好的，谢谢。
