### ISSUE TITLE
将onnx模型移植到了手机端，每次单张的预测速度很慢，能否支持批量预测？

### ISSUE THREAD

**Issue by zhangjh** [OFA-Sys/Chinese-CLIP#163]
如题所示，端上本来性能就有限，onnx模型能否支持批量预测？

**Comment by zhangjh** [comment]
根据作者的提示，在ChatGpt的加持之下，我修改了一下源码，已经成功把模型导出为可以支持批量处理的了。不过在端上的处理效果好像不像我想的那样：是单次处理的n倍。。😂😂
anyway，既然你们也考虑对这个支持，我把我的修改提交一下PR吧，不过我的主要技术栈主要是Java，对Python不是很了解，也不知道改的对不对，作者帮忙确认一下，如果没问题的话，可以考虑merge一下。

**Comment by yangapku** [comment]
感谢感谢，我们会尽快check下哈
