### ISSUE TITLE
训练数据到达亿级别后，训练出现内存泄漏，导致自动被kill。请问大佬在进行原始的2亿数据训练的时候有遇到相关问题不

### ISSUE THREAD

**Issue by Xujianzhong** [OFA-Sys/Chinese-CLIP#170]

**Comment by yangapku** [comment]
您好，实际上我们在内部预训练时，有用到一些阿里内部的数据引擎，并不是完全按照LMDB的格式，也希望您可以帮我们看下开源版本有没有更好的方案哈~

**Comment by oysz2016** [comment]
> 您好，实际上我们在内部预训练时，有用到一些阿里内部的数据引擎，并不是完全按照LMDB的格式，也希望您可以帮我们看下开源版本有没有更好的方案哈~

请问数据泄漏是由于dataset引起的吗？
