### ISSUE TITLE
如何在多机多卡、全局损失的情况下估计显存占用？

### ISSUE THREAD

**Issue by Adenialzz** [OFA-Sys/Chinese-CLIP#171]
在全局损失设置下，当使用多个节点进行训练时，GPU显存占用将远高于使用单个节点进行训练。请问此时应该如何估计多个节点的GPU显存占用？

**Comment by DtYXs** [comment]
不知道您说的全局损失是指哪一部分，您可以参考[使用FlashAttention加速Chinese-CLIP](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/flash_attention.md)文档中最后给出的表格来大致估计一下，或者采用二分法设置batchsize来实际找合适的范围。

**Comment by Adenialzz** [comment]
请问--gather-with-grad参数具体怎么理解？

**Comment by yangapku** [comment]
您好，您可以结合具体代码来看下这个参数的作用。由于我们在对比学习时，对于多卡分布式训练的情况，每张卡会把其他卡上的样本表征，利用卡间通信传过来作为负例。这个参数，就控制了梯度是否沿着通信过来的负样本反传回其他卡上。
