### ISSUE TITLE
COCO 测试集

### ISSUE THREAD

**Issue by songtianhui** [OFA-Sys/Chinese-CLIP#175]
作者您好，我想确认一下 coco retrieval 测评使用的集合。按照 COCO-CN 论文中，COCO-CN 的测试集为1k张图片和(1k手写+5k翻译)共6k条caption，请问Chinese CLIP汇报的指标是使用的多少条文本caption，如何选取的。
Chinese CLIP 论文中提到
> Flickr30K-CN and COCO-CN are built from the classical datasets Flickr30K and MSCOCO-1K whose texts are translated into Chinese.

这有些让人困惑。MSCOCO-1k 又是哪个集合。

**Comment by yangapku** [comment]
https://github.com/li-xirong/coco-cn

**Comment by songtianhui** [comment]
感谢您的回复！我仔细阅读了 COCO-CN 工作，所以我首先想确认测评是在 COCO-CN 的测试集上进行的对吧？
即 1000张图片，每张图片6个文本caption。是使用全部的 1000 图片和 6000个 caption来进行t2i和i2t的retrieval吗？
此外，我依然感到疑惑Chinese CLIP论文中提到的 MSCOCO-1k 是哪个数据集。

**Comment by DtYXs** [comment]
您好，COCO-CN测评是在测试集，共有1000图像和1053文本，跟论文中对比的Baseline工作是一致的

**Comment by songtianhui** [comment]
明白了，感谢！
