### ISSUE TITLE
有没有比Resnet50还小的模型？

### ISSUE THREAD

**Issue by 205418367** [OFA-Sys/Chinese-CLIP#176]

**Comment by DtYXs** [comment]
[模型规模 & 下载链接](https://github.com/OFA-Sys/Chinese-CLIP#%E6%A8%A1%E5%9E%8B%E8%A7%84%E6%A8%A1--%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5)目前Chinese CLIP最小的规模就是RN50
