### ISSUE TITLE
测试集问题

### ISSUE THREAD

**Issue by L1Shupe1** [OFA-Sys/Chinese-CLIP#183]
请问对于示例提供的测试集格式，如何计算召回呢？
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/87518479/b89bca8c-31f5-4498-94c8-93c16071b73f)
测试集如果不指定文本对应的图片的话，后续如何计算得到分数呢？
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/87518479/673a60cc-050f-46ee-8ab0-39bf8f2d9699)
readme里对于测试集的描述是这样的，是只有test没有image的形式

**Comment by L1Shupe1** [comment]
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/87518479/c5ed2a2b-deec-4b09-b7ec-c3af611cd2c4)
我如同readme中布置测试集后，得到的召回是0:
{"success": true, "score": 0.0, "scoreJson": {"score": 0.0, "mean_recall": 0.0, "r1": 0.0, "r5": 0.0, "r10": 0.0}}
请问如果这样布置测试集，如何评估测试结果呢

**Comment by yangapku** [comment]
您好，readme这里针对的测试集，指的是像MUGE官方测试集类似的，需要在官网提交后由官方反馈测试集分数的情况哈。对于您自己评测，还是需要测试集数据中自带ground-truth的image_id，否则模型自己也是无法判断召回率的哈。
