### ISSUE TITLE
训练脚本运行报错main.py: 第17行：from cn_clip.clip.model import convert_weights, convert_state_dict, resize_pos_embed, CLIP  提示cn_clip.clip.model中没有convert_state_dict这个函数

### ISSUE THREAD

**Issue by wjpstudy** [OFA-Sys/Chinese-CLIP#185]

**Comment by wjpstudy** [comment]
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/93515310/2389f173-aae5-4cc0-88ef-5d33b81f7849)

**Comment by wjpstudy** [comment]
您好，已解决。问题在于虚拟环境里安装了cn_clip这个包，和项目代码Chinese-CLIP/cn_clip中的cn_clip重名所导致。

**Comment by wjpstudy** [comment]
您好，感谢您的回复，这个问题已解决。目前已在官方给的MUGE数据集上跑通整个流程。感谢！

**Comment by FangXinyu-0913** [comment]
> 您好，感谢您的回复，这个问题已解决。目前已在官方给的MUGE数据集上跑通整个流程。感谢！

您好想问一下您是怎么解决的，我这边仍旧会有这样的问题...而且代码版本也是最新的

**Comment by wjpstudy** [comment]
1. 出现这个问题的主要原因在于：通过pip安装的cn_clip和github上拉取的项目中的cn_clip同名导致的，以至于解释器会自动在外部库中引入通过pip安装的cn_clip，而通过pip安装的cn_clip里确实没有convert_state_dict这个函数；
2. 解决方式：在引入cn_clip中的文件时，可以通过绝对路径或者更改github上拉取的项目中的cn_clip名称，从而让解释器能够找到github上拉取的最新版本的cn_clip即可；








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月29日(星期二) 上午10:52
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] 训练脚本运行报错main.py: 第17行：from cn_clip.clip.model import convert_weights, convert_state_dict, resize_pos_embed, CLIP  提示cn_clip.clip.model中没有convert_state_dict这个函数 (Issue #185)





  
您好，感谢您的回复，这个问题已解决。目前已在官方给的MUGE数据集上跑通整个流程。感谢！
  
您好想问一下您是怎么解决的，我这边仍旧会有这样的问题...而且代码版本也是最新的

**Comment by FangXinyu-0913** [comment]
> 

好的，已经解决了，谢谢！
