### ISSUE TITLE
支持开源的其他VIT预训练权重么

### ISSUE THREAD

**Issue by liszekei** [OFA-Sys/Chinese-CLIP#186]
hi，如题，我看model中的VIT是作者手动实现的，请问可以加载例如基于timm 的VIT训练的权重么。
谢谢～

**Comment by DtYXs** [comment]
您好，由于Chinese-CLIP的ViT经过中文图文pair预训练，因此如果您想要加载其他权重，应该还需要再次训练让模型对齐图像和文本才能取得正常的效果
