### ISSUE TITLE
希望以debug断点调试的形式运行cn_clip/training/main.py

### ISSUE THREAD

**Issue by wjpstudy** [OFA-Sys/Chinese-CLIP#188]
您好，以官方给的MUGE数据集为例，muge_finetune_vit-b-16_rbt-base.sh脚本能够正常运行，我现在希望能够在pycharm中以debug断点调试的形式运行cn_clip/training/main.py ，而不是以muge_finetune_vit-b-16_rbt-base.sh脚本的形式运行cn_clip/training/main.py ，以便学习clip整个微调的过程 ，该如何操作？muge_finetune_vit-b-16_rbt-base.sh脚本中的GPUS_PER_NODE=1  WORKER_CNT=1 export MASTER_ADDR=localhost export MASTER_PORT=8514 export RANK=0 该如何加入到cn_clip/training/main.py的运行配置中，以达到断点调试的目的？我现在处理方式是：import os  os.environ["CUDA_VISIBLE_DEVICES"] = "1" os.environ["GPUS_PER_NODE"] = "1" os.environ["WORKER_CNT"] = "1" os.environ["MASTER_ADDR"] = "localhost" os.environ["MASTER_PORT"] = "8515" os.environ["RANK"] = "0"  会以下报错：
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/93515310/bcba9cec-08d0-4563-a757-f1a0f0cf6663)

**Comment by TanLo** [comment]
你好，可以通过配置以下环境变量实现单卡debug：
`MASTER_ADDR=localhost
MASTER_PORT=8514
PYTHONPATH=${PYTHONPATH}:./cn_clip
LOCAL_RANK=0
RANK=0
WORLD_SIZE=1`

**Comment by wjpstudy** [comment]
十分感谢  按照您的指导，已经完成单卡debug。
