### ISSUE TITLE
为什么在MUGE验证集上相比COCO-CN和Flickr-CN效果明显比其他模型更好

### ISSUE THREAD

**Issue by JH-Xie** [OFA-Sys/Chinese-CLIP#19]
在COCO-CN和Flickr-CN上，chinese-clip RN50小模型相比wukong/R2D2的vit-b效果差不多或者落后，但是在MUGE上却大幅领先，请问这是什么原因？

**Comment by yangapku** [comment]
您好，我们初步判断主要原因是因为MUGE来自中文原生的数据，而其他两个数据集仍然是英文数据集的翻译或中文适配版本，所以我们在中文原生图文数据上的优势更加显著。

**Comment by JH-Xie** [comment]
> 您好，我们初步判断主要原因是因为MUGE来自中文原生的数据，而其他两个数据集仍然是英文数据集的翻译或中文适配版本，所以我们在中文原生图文数据上的优势更加显著。

您好，感谢您的回复。我有注意到无论是wukong、R2D2以及chinese-clip，使用的训练数据都是以原生的中文数据为主。MUGE的数据主要是商品描述，与原生中文数据其实有一定差距，Flickr-CN是人工翻译，COCO-CN更是直接人工注释，我理解这两个测试集相比MUGE其实会更接近原始的中文。

**Comment by yangapku** [comment]
您好，除了您提到的预训练数据，还有个关键的细节需要您关注哈。wukong和R2D2据我们了解，都是在预训练过程中全程freeze图像侧的做法（LiT训练），也就是说即使数据以原生的中文数据为主，但实际上图像侧仍然没有用这部分数据训练过，中文数据只是用于只是把文本侧表征对齐到图像侧。而我们为了进一步提升效果（尤其是在中文原生数据上提升效果），进一步使用二阶段策略，一起训练图像和文本侧，也因此在下游效果能进一步提升。具体指标，您可以参见技术报告Figure 2哈，实际上从曲线来看，这种适配对于MUGE和MSCOCO-CN这两个非翻译数据集的提升是很显著的，对于MUGE更显著一些（可能因为MUGE图像也是中文领域来源），也许能够解答您的问题。
