### ISSUE TITLE
请问跟openai开源的clip相比，哪个更好一些呢？

### ISSUE THREAD

**Issue by 937739823** [OFA-Sys/Chinese-CLIP#190]
请问跟openai开源的clip相比，哪个更好一些呢？

**Comment by yangapku** [comment]
我们的结果可以参见技术报告哈，在中文图文表征（双塔模型）方面，目前Chinese-CLIP是最优的开源模型。在中文图文检索MUGE、COCO-CN和Flickr30K-CN都取得了最优水平，同时也具有一定的英文理解能力，可以体验我们的检索和视觉分类demo哈。

**Comment by yangapku** [comment]
@Pass-O-Guava 不太熟悉easynlp哈，我们不是一个项目，没有任何关系。在中文图文特征方面，据我所知目前chinese-clip仍然是您的最佳选择

**Comment by StephanPan** [comment]
可以直接用openai clip的api加载Chinese-clip的权重吗？
