### ISSUE TITLE
这个项目可以做图像描述任务吗

### ISSUE THREAD

**Issue by yazheng0307** [OFA-Sys/Chinese-CLIP#197]

**Comment by yangapku** [comment]
您好，建议图像描述任务，考虑我们最新的[通义千问多模态开源模型](https://github.com/QwenLM/Qwen-VL)，或我们先前的工作[OFA-Sys/OFA](https://github.com/OFA-Sys/OFA)哈，中文CLIP主要用于图文特征提取和零样本视觉分类使用。
