### ISSUE TITLE
申请处理好的COCO-CN

### ISSUE THREAD

**Issue by czczup** [OFA-Sys/Chinese-CLIP#199]
作者您好，我已获得coco-cn的许可，希望获得预处理的coco-cn数据，万分感谢！
我的邮箱是chenzhe98@smail.nju.edu.cn

<img width="634" alt="image" src="https://github.com/OFA-Sys/Chinese-CLIP/assets/23737120/f940c0b6-383f-4be2-a908-a9890d4eec4e">

**Comment by yangapku** [comment]
您好，请您提供一个邮箱哈

**Comment by czczup** [comment]
您好，邮箱是chenzhe98@smail.nju.edu.cn

**Comment by czczup** [comment]
> 已发送哈

感谢！

**Comment by daicver** [comment]
相同的需求，希望能获得处理好的coco-cn数据集，感谢。
接收邮箱：daicver@gmail.com
![Uploading 截屏2024-03-07 21.23.46.png…]()

**Comment by herrylu** [comment]
作者您好，已将coco-cn许可信息发您yangapku@gmail.com邮箱，希望能获得处理好的coco-cn数据集，感谢。
我的邮箱是2011301360110@mail.ncut.edu.cn

**Comment by SplashCloud** [comment]
作者您好，已将coco-cn许可信息发您yangapku@gmail.com邮箱，希望能获得处理好的coco-cn数据集，感谢。
我的邮箱是hczheng2024@gmail.com
