### ISSUE TITLE
数据集组成有哪些

### ISSUE THREAD

**Issue by zhangqianYY** [OFA-Sys/Chinese-CLIP#2]
你好，数据集除了包含wukong1亿图文对，还有哪些组成部分呢，另外数据集考虑开源么？

**Comment by yangapku** [comment]
您好，预训练数据集除了wukong外，主要包含的就是LAION-5B（https://laion.ai/laion-5b-a-new-era-of-open-large-scale-multi-modal-datasets/）多语言图文对的中文部分（约1亿），这两部分数据都是可以公开下载的
