### ISSUE TITLE
import cn_clip出错UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 1564: illegal multibyte sequence

### ISSUE THREAD

**Issue by bigmarten** [OFA-Sys/Chinese-CLIP#20]
import cn_clip.clip as clip
发生异常: UnicodeDecodeError
Traceback (most recent call last):
  File "D:\develop\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\develop\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\saizong\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\saizong\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\saizong\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "D:\develop\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\develop\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\develop\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\develop\workspace\today_video\clipcn.py", line 5, in <module>
    import cn_clip.clip as clip
  File "D:\develop\anaconda3\Lib\site-packages\cn_clip\clip\__init__.py", line 3, in <module>
    _tokenizer = FullTokenizer()
  File "D:\develop\anaconda3\Lib\site-packages\cn_clip\clip\bert_tokenizer.py", line 170, in __init__
    self.vocab = load_vocab(vocab_file)
  File "D:\develop\anaconda3\Lib\site-packages\cn_clip\clip\bert_tokenizer.py", line 132, in load_vocab
    token = convert_to_unicode(reader.readline())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 1564: illegal multibyte sequence

请问如何处理？谢谢！

**Comment by yangapku** [comment]
收到，我们看下，请您稍等

**Comment by yangapku** [comment]
@bigmarten 您好，请您更新下代码（如果使用源代码请pull最新commit，如果使用pip包则更新到最新版本），再试下哈

**Comment by bigmarten** [comment]
更新后变成如下错误：
Traceback (most recent call last):
&nbsp; File "D:\develop\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
&nbsp; &nbsp; "__main__", mod_spec)
&nbsp; File "D:\develop\anaconda3\lib\runpy.py", line 85, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "c:\Users\saizong\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module&gt;
&nbsp; &nbsp; cli.main()
&nbsp; File "c:\Users\saizong\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
&nbsp; &nbsp; run()
&nbsp; File "c:\Users\saizong\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
&nbsp; &nbsp; runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
&nbsp; File "D:\develop\anaconda3\lib\runpy.py", line 263, in run_path
&nbsp; &nbsp; pkg_name=pkg_name, script_name=fname)
&nbsp; File "D:\develop\anaconda3\lib\runpy.py", line 96, in _run_module_code
&nbsp; &nbsp; mod_name, mod_spec, pkg_name, script_name)
&nbsp; File "D:\develop\anaconda3\lib\runpy.py", line 85, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "d:\develop\workspace\today_video\clipcn.py", line 5, in <module&gt;
&nbsp; &nbsp; import cn_clip.clip as clip
&nbsp; File "D:\develop\anaconda3\Lib\site-packages\cn_clip\clip\__init__.py", line 4, in <module&gt;
&nbsp; &nbsp; from .utils import load_from_name, available_models, tokenize, image_transform, load
&nbsp; File "D:\develop\anaconda3\Lib\site-packages\cn_clip\clip\utils.py", line 10, in <module&gt;
&nbsp; &nbsp; from torchvision.transforms import Compose, ToTensor, Normalize, Resize, InterpolationMode
&nbsp; File "D:\develop\anaconda3\Lib\site-packages\torchvision\__init__.py", line 5, in <module&gt;
&nbsp; &nbsp; from torchvision import datasets, io, models, ops, transforms, utils
&nbsp; File "D:\develop\anaconda3\Lib\site-packages\torchvision\models\__init__.py", line 16, in <module&gt;
&nbsp; &nbsp; from .maxvit import *
&nbsp; File "D:\develop\anaconda3\Lib\site-packages\torchvision\models\maxvit.py", line 3, in <module&gt;
&nbsp; &nbsp; from typing import Any, Callable, List, Optional, OrderedDict, Sequence, Tuple
ImportError: cannot import name 'OrderedDict' from 'typing' (D:\develop\anaconda3\lib\typing.py)



J.bigmarten
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] import cn_clip出错UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 1564: illegal multibyte sequence (Issue #20)





 
@bigmarten 您好，请您更新下代码（如果使用源代码请pull最新commit，如果使用pip包则更新到最新版本），再试下哈

**Comment by yangapku** [comment]
您好，这个看起来更像是python版本和torchvision库的兼容问题，您方便提供下环境里面python、pytorch和torchvision的具体版本吗？

**Comment by yangapku** [comment]
您也可以参考下这个帖子哈 https://huaweicloud.csdn.net/63803d40dacf622b8df86987.html

**Comment by bigmarten** [comment]
python 3.7.1
torch 1.13.0
torchvision 0.14.0

&nbsp;


J.bigmarten
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OFA-Sys/Chinese-CLIP] import cn_clip出错UnicodeDecodeError: &#39;gbk&#39; codec can&#39;t decode byte 0x81 in position 1564: illegal multibyte sequence (Issue #20)





 
您好，这个看起来更像是python版本和torchvision库的兼容问题，您方便提供下环境里面python、pytorch和torchvision的具体版本吗？

**Comment by yangapku** [comment]
恩恩，那确实是了，您的python 3.7版本有些过于低了

**Comment by yangapku** [comment]
您可以考虑以下几种做法，应该都可以：

**Comment by yangapku** [comment]
@bigmarten  您可以考虑以下几种做法，选择其一即可：
1. python升级到更高的3.7.x版本（>= 3.7.2）。python 3.7.1小版本过低，三方包很多已经不再兼容
2. torch和对应的torchvision降降级，torchvision从0.14降到0.13版本（`pytorch==1.12.1 torchvision==0.13.1`）
3. 参考帖子 https://huaweicloud.csdn.net/63803d40dacf622b8df86987.html ，把import有问题的torchvision库对应文件修改下

**Comment by bigmarten** [comment]
按你提供的方法解决了问题，进一步请教：
1.你是从哪知道torch，torchvision对应版本的？
2.demo里的Available models进度条是在下载模型吧，只看到json格式，下载700多M模型存什么位置？
3.官方有没有新闻类应用的案例或者其他行业案例。
谢谢！
&nbsp;


J.bigmarten
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang ***@***.***&gt;; 
发送时间: 2022年11月29日(星期二) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OFA-Sys/Chinese-CLIP] import cn_clip出错UnicodeDecodeError: &#39;gbk&#39; codec can&#39;t decode byte 0x81 in position 1564: illegal multibyte sequence (Issue #20)





 
@bigmarten  您可以考虑以下几种做法，选择其一即可：
  
python升级到更高的3.7.x版本（&gt;= 3.7.2）。python 3.7.1小版本过低，三方包很多已经不再兼容
 
torch和对应的torchvision降降级，torchvision从0.14降到0.13版本（pytorch==1.12.1 torchvision==0.13.1）
 
参考帖子 https://huaweicloud.csdn.net/63803d40dacf622b8df86987.html ，把import有问题的torchvision库对应文件修改下

**Comment by yangapku** [comment]
您好，torch和torchvision的对应版本，可以从torch的官方网站查到哈https://pytorch.org/get-started/previous-versions/ ，里面都是对应的版本绑定在一起安装的。 您使用API时初次下载模型，下载的位置是通过代码`model, preprocess = load_from_name("ViT-B-16", device=device, download_root='./')`中的`download_root`指定的，我们的示例代码中`download_root='./'`，即将下载到当前命令行的目录`./`下，当然也是可以在使用时指定其他的路径。关于应用案例，目前我们也在积极准备更多案例中，目前集团内部一些团队已经在业务流程中加入了我们的模型，详情请您期待我们后续的更多发布！

**Comment by bigmarten** [comment]
你们有提供clip中文prompt模板吗？哪里可以下载？




J.bigmarten
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] import cn_clip出错UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 1564: illegal multibyte sequence (Issue #20)





 
@bigmarten  您可以考虑以下几种做法，选择其一即可：
  
python升级到更高的3.7.x版本（&gt;= 3.7.2）。python 3.7.1小版本过低，三方包很多已经不再兼容
 
torch和对应的torchvision降降级，torchvision从0.14降到0.13版本（pytorch==1.12.1 torchvision==0.13.1）
 
参考帖子 https://huaweicloud.csdn.net/63803d40dacf622b8df86987.html ，把import有问题的torchvision库对应文件修改下

**Comment by yangapku** [comment]
有的哈！

首先，我们有一个在线做图片分类的demo，欢迎体验：https://huggingface.co/spaces/OFA-Sys/chinese-clip-zero-shot-image-classification ，这个demo以"**一张{}的图片。**"作为prompt模板，{}部分用来替换分类标签。

然后，关于用代码跑零样本图片分类任务实验，具体运行方法，请您参见readme[零样本图像分类](https://github.com/OFA-Sys/Chinese-CLIP#%E9%9B%B6%E6%A0%B7%E6%9C%AC%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB)部分。关于我们技术报告和readme中，汇报零样本图像分类结果使用的[ELEVATER](https://eval.ai/web/challenges/challenge-page/1832)中文版本benchmark（几个常见英文数据集的中文版），我们最新的代码库提供了[下载链接](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/zeroshot_dataset.md)。下载包中收录了ELEVATER各子数据集使用的中文label集合，各子数据集使用的中文prompt模板则请您参见[cvinw_zeroshot_templates.py](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/cn_clip/eval/cvinw_zeroshot_templates.py)，我们的代码支持对多个prompt进行集成。您也可以参照我们处理ELEVATER的代码及数据格式，对自己的分类数据集进行尝试。另外，[imagenet_zeroshot_templates.py](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/cn_clip/eval/imagenet_zeroshot_templates.py)是我们从wukong的工作直接引用的ImageNet 中文翻译prompt模板和中文label集合，但我们在ImageNet上面相关的优化工作还在进行中，如果您有需要也可以先使用。

**Comment by yangapku** [comment]
关于零样本图片分类的问题，建议您新开一个相关issue，也便于社区其他用户参考。这个issue如果已经解决的话，我就先准备关闭了。如果觉得我们的代码库有帮助，欢迎给Chinese-CLIP送上一个star哈！ ❤️
