### ISSUE TITLE
能提供一下从.pt转到.bin格式的思路吗

### ISSUE THREAD

**Issue by 2132660698** [OFA-Sys/Chinese-CLIP#202]
看到huggingface同时提供了.pt.bin
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/94035926/d397d62c-9c44-4172-b29d-c3101bd9c7d5)

**Comment by yangapku** [comment]
您好，我们在transformers库中提供了一个转换脚本哈，您可以参见 https://github.com/huggingface/transformers/blob/main/src/transformers/models/chinese_clip/convert_chinese_clip_original_pytorch_to_hf.py

**Comment by 2132660698** [comment]
好的，非常感谢，已经解决问题了

**Comment by Yang-bug-star** [comment]
@2132660698 你好我想问下转换为hf格式时的config文件是要自己更改吗，能自动保存吗

**Comment by Yang-bug-star** [comment]
以及那个preprocessor_config.json是不是对所有模型通用不用改的
