### ISSUE TITLE
基于ModelScope库的知识蒸馏微调功能报错

### ISSUE THREAD

**Issue by wjpstudy** [OFA-Sys/Chinese-CLIP#208]
9.8更新的支持基于[ModelScope](https://github.com/modelscope/modelscope)库的[知识蒸馏微调功能](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/distillation.md)，在运行Chinese-CLIP-master/cn_clip/training/main.py微调的过程中，在初始化initialize model from .cache/modelscope/hub/damo/multi-modal_team-vit-large-patch14_multi-modal-similarity的时候报错：RuntimeError: Error(s) in loading state_dict for TEAM:
	Unexpected key(s) in state_dict: "text_model.bert.embeddings.position_ids". 
具体报错如下：
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/93515310/8f7702fc-62a7-476d-af4b-12fc79928fd2)
请问该如何解决？期待您的回复，感谢！

**Comment by wjpstudy** [comment]
具体报错如下：

**Comment by wuziheng** [comment]
提供一下具体的modelscope 版本。

**Comment by wjpstudy** [comment]
您好，安装的modelscope版本为1.9.0  
Chinese-CLIP-master/cn_clip/training/main.py代码中的
 teacher_model_dict = {
            "damo/multi-modal_team-vit-large-patch14_multi-modal-similarity" : {"model": "image_model"},
            "damo/multi-modal_rleg-vit-large-patch14" : {"model": "encode_image"},
            "damo/multi-modal_clip-vit-huge-patch14_zh" : {"clip_model": "encode_image"},
            "damo/multi-modal_clip-vit-large-patch14_zh" : {"clip_model": "encode_image"},
        }

**Comment by Jaskr616** [comment]
你好，modelscope版本是跟我们使用的是一致的。
可能是环境中transformer版本不一致的问题，可以尝试4.27.4版本的transformer。

**Comment by wjpstudy** [comment]
非常感谢！确实是transformers版本导致的。我之前用的是 4.31.0 ,改为4.27.4版本的transformers就能正常微调了。
