### ISSUE TITLE
为什么转onnx时会生成extra_file部分，能不能不要这部分，将所有的信息都放到onnx模型中

### ISSUE THREAD

**Issue by noseding** [OFA-Sys/Chinese-CLIP#210]

**Comment by Linranran** [comment]
# 保存 FP16 模型
        vision_fp32_onnx_model = load_model(vision_fp32_onnx_path)
        vision_fp16_onnx_model = convert_float_to_float16(vision_fp32_onnx_model, keep_io_types=True, disable_shape_infer=True)
        # 将模型转换为 FP16
        onnx.save(onnx_model_fp16, f"{args.save_onnx_path}.img.fp16.onnx")
        # if args.model_arch == "ViT-H-14":
        #     packing_small_onnx_files(vision_fp32_onnx_path)
        #     vision_fp32_onnx_hasextra = True
        # # convert vision FP16 ONNX model based on the FP32 model
        # vision_fp16_onnx_path = f"{args.save_onnx_path}.img.fp16.onnx"
        # vision_fp32_onnx_model = load_model(vision_fp32_onnx_path)
        # vision_fp16_onnx_model = convert_float_to_float16(vision_fp32_onnx_model, keep_io_types=True, disable_shape_infer=True)
        # save_model(vision_fp16_onnx_model,
        #             vision_fp16_onnx_path,
        #             location="{}.extra_file".format(os.path.split(vision_fp16_onnx_path)[1]),
        #             save_as_external_data=True,
        #             all_tensors_to_one_file=True,
        #             size_threshold=1024,
        #             convert_attribute=True)
