### ISSUE TITLE
prompt ensembling

### ISSUE THREAD

**Issue by 22wei22** [OFA-Sys/Chinese-CLIP#23]
prompt ensembling已经开源了么

**Comment by yangapku** [comment]
您好，已经开源了！具体运行方法，请您参见readme[零样本图像分类](https://github.com/OFA-Sys/Chinese-CLIP#%E9%9B%B6%E6%A0%B7%E6%9C%AC%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB)部分。关于我们技术报告和readme中，汇报零样本图像分类结果使用的[ELEVATER](https://eval.ai/web/challenges/challenge-page/1832)中文版本benchmark，我们最新的代码库提供了[下载链接](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/zeroshot_dataset.md)。下载包中收录了ELEVATER各子数据集使用的中文label集合，各子数据集使用的prompt则请您参见[cvinw_zeroshot_templates.py](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/cn_clip/eval/cvinw_zeroshot_templates.py)，我们的代码支持对多个prompt进行集成。您也可以参照我们处理ELEVATER的代码，对自己的分类数据集进行尝试。另外，[imagenet_zeroshot_templates.py](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/cn_clip/eval/imagenet_zeroshot_templates.py)是我们从wukong的工作直接引用的ImageNet prompt和中文label集合，但我们在ImageNet上面相关的优化工作还在进行中，如果您有需要也可以先使用。

如果有更多问题，欢迎您继续提问！
