### ISSUE TITLE
自建数据集微调的疑问

### ISSUE THREAD

**Issue by MarcoZuo** [OFA-Sys/Chinese-CLIP#233]
在进行tsv和jsonl文件序列化生成LMDB文件时，使用如下命令（DATAPATH已经被替换）：
`python Chinese-CLIP/cn_clip/preprocess/build_lmdb_dataset.py \ 
      --data_dir RailwayBreakdown/datasets/Railway_Track_fault_Detection_Updated --splits train,valid,test`
总是生成失败，只能生成一个imgs文件夹，没有pairs，且mdb文件大小明显偏小（图1），或者报错（图2）
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/57880920/baca823f-d78c-45c8-a883-ce6ce2400178)
图1
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/57880920/ff7e943f-02d7-4388-abf9-d21018ef372a)
图2

**Comment by MarcoZuo** [comment]
另外测试了本项目提供的Flickr30k-CN数据集，删除lmdb文件夹后再运行生成的也是如图1所示的问题
![image](https://github.com/OFA-Sys/Chinese-CLIP/assets/57880920/caa71ebe-363f-478b-8515-1a79e4214ea9)

**Comment by Lw1244204021** [comment]
你好 ，请问你是怎么解决的呀？
