### ISSUE TITLE
预训练模型授权洽詢

### ISSUE THREAD

**Issue by fann1993814** [OFA-Sys/Chinese-CLIP#234]
先感谢本项目Chinese-CLIP所帶來的帮助。

本人有商业情境需求使用，因此请问预训练模型授权支援商用吗？若有商用授权有申请渠道的提供吗？

看到本项目的源码是采MIT，然后ModelScope中是采用Apache2.0，然而Huggingface hub没有提及。因此提出此疑问。

**Comment by yangapku** [comment]
您好，可以商用哈，以我们的MIT许可证为准即可~
