### ISSUE TITLE
你好，我想在自己的数据集上微调，两张3090够吗

### ISSUE THREAD

**Issue by biedaxiaohua** [OFA-Sys/Chinese-CLIP#243]

**Comment by yangapku** [comment]
应该是可以的，可以参考我们的notebook尝试下哈，里面的要求基本是最低配置要求了

**Comment by L1n111ya** [comment]
> 应该是可以的，可以参考我们的notebook尝试下哈，里面的要求基本是最低配置要求了

您好，我想问一下哪里有notebook，这边没有找到

**Comment by ctgushiwei** [comment]
两张3090自己做微调是可以的，我做过实验
