### ISSUE TITLE
请问这个项目有图片转成中文描述的功能吗，类似clip的interrogator

### ISSUE THREAD

**Issue by mmix574** [OFA-Sys/Chinese-CLIP#247]
[clip_interrogator.py](https://github.com/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator/clip_interrogator.py)

我希望通过图片可以解析出文字，想知道这个是否可行，或者有没有相关的资料呢，谢谢！

**Comment by yangapku** [comment]
您好，关于图像描述任务，欢迎参见我们团队的最新工作Qwen-VL哈~ 欢迎关注通义千问系列模型
https://github.com/QwenLM/Qwen-VL
