### ISSUE TITLE
模型有点大呀，2个G，会有小一些的模型提供吗

### ISSUE THREAD

**Issue by lonngxiang** [OFA-Sys/Chinese-CLIP#3]

**Comment by lonngxiang** [comment]
> 这需求很赞 我们之后会推小模型，尽量快弄完吧。能说下你对size大小的期待么？

用过正常500M内，CLIP官方大小也差不多这个大小；另外文本和图像模型能分别提供就更好了

**Comment by JustinLin610** [comment]
> > 这需求很赞 我们之后会推小模型，尽量快弄完吧。能说下你对size大小的期待么？
> 
> 用过正常500M内，CLIP官方大小也差不多这个大小；另外文本和图像模型能分别提供就更好了

啊我懂了，误会你意思。。是因为我们把optimizer state也打进去了，这样才能finetune。我们混合精度训的，拎个state dict出来的话应该是现在1/6大小。双塔分开也没问题，稍等下我们这两天更上去

**Comment by lonngxiang** [comment]
> > > 这需求很赞 我们之后会推小模型，尽量快弄完吧。能说下你对size大小的期待么？
> > 
> > 
> > 用过正常500M内，CLIP官方大小也差不多这个大小；另外文本和图像模型能分别提供就更好了
> 
> 啊我懂了，误会你意思。。是因为我们把optimizer state也打进去了，这样才能finetune。我们混合精度训的，拎个state dict出来的话应该是现在1/6大小。双塔分开也没问题，稍等下我们这两天更上去

嗯期待哈，再提个小需求哈，demo案例能提供各简单点的不，demo不用使用向量库召回，直接能运行直观看效果，还是像CLIP那种，几行代码就能看效果

**Comment by JustinLin610** [comment]
> > > > 这需求很赞 我们之后会推小模型，尽量快弄完吧。能说下你对size大小的期待么？
> > > 
> > > 
> > > 用过正常500M内，CLIP官方大小也差不多这个大小；另外文本和图像模型能分别提供就更好了
> > 
> > 
> > 啊我懂了，误会你意思。。是因为我们把optimizer state也打进去了，这样才能finetune。我们混合精度训的，拎个state dict出来的话应该是现在1/6大小。双塔分开也没问题，稍等下我们这两天更上去
> 
> 嗯期待哈，再提个小需求哈，demo案例能提供各简单点的不，demo不用使用向量库召回，直接能运行直观看效果，还是像CLIP那种，几行代码就能看效果

诶你是不是没看到更新的API.. 那个就和CLIP一样了

**Comment by lonngxiang** [comment]
> > > > > 这需求很赞 我们之后会推小模型，尽量快弄完吧。能说下你对size大小的期待么？
> > > > 
> > > > 
> > > > 用过正常500M内，CLIP官方大小也差不多这个大小；另外文本和图像模型能分别提供就更好了
> > > 
> > > 
> > > 啊我懂了，误会你意思。。是因为我们把optimizer state也打进去了，这样才能finetune。我们混合精度训的，拎个state dict出来的话应该是现在1/6大小。双塔分开也没问题，稍等下我们这两天更上去
> > 
> > 
> > 嗯期待哈，再提个小需求哈，demo案例能提供各简单点的不，demo不用使用向量库召回，直接能运行直观看效果，还是像CLIP那种，几行代码就能看效果
> 
> 诶你是不是没看到更新的API.. 那个就和CLIP一样了

抱歉，这会看到了

**Comment by SmileTAT** [comment]
> 
感谢开源~请问之后推的小模型大概是什么量级的？可以支持在端侧运行吗?

**Comment by yangapku** [comment]
您好，这个issue提问的已经是很早先的内容了~ 现在我们最新提供的开源ckpt，已经把大家不太用得到的optimizer state移除了，大大缩小了ckpt文件的大小。目前根据[readme](https://github.com/OFA-Sys/Chinese-CLIP#model_card)的描述，我们提供了5个不同规模的模型供下载，**模型骨架结构**和**参数规模**已经在readme对应表格列出哈。5个开源ckpt文件的**文件体积**，从小到大分别是294MB（CN-CLIP<sub>RN50</sub>）、718MB（CN-CLIP<sub>ViT-B/16</sub>）、1.51GB（CN-CLIP<sub>ViT-L/14</sub>）、1.51GB（CN-CLIP<sub>ViT-L/14@336px</sub>）和3.57GB（CN-CLIP<sub>ViT-H/14</sub>）。我们将在最近几天更新模型转为ONNX和TensorRT格式的一个示例流程，方便大家参考进行模型部署。如果您对于模型规模大小还有进一步轻量化的要求，也可以先反馈给我们，我们看下能不能在后续更新中加以实现。
