### ISSUE TITLE
运行zeroshot_eval.sh遇到问题，望作者解答

### ISSUE THREAD

**Issue by zhou-wenn** [OFA-Sys/Chinese-CLIP#30]
作者您好，我使用如下命令运行zeroshot_eval.sh出现报错，是不是我的命令书写哪里存在问题呢，谢谢。 ${DATAPATH}文件夹命名为data。

错误如下：
```
$ bash run_scripts/zeroshot_eval.sh 0 \
>     data fgvc-aircraft-2013b-variants102 \
>     ViT-B-16 RoBERTa-wwm-ext-base-chinese \
>     data/ckpt
Traceback (most recent call last):
  File "E:/Project/CLIP/Chinese-CLIP-master/cn_clip/eval/zeroshot_evaluation.py", line 18, in <module>
    from cn_clip.eval.data import get_zeroshot_dataset, _preprocess_text
ImportError: cannot import name 'get_zeroshot_dataset' from 'cn_clip.eval.data' (E:\Anaconda\envs\PyTorch\lib\site-packages\cn_clip\eval\data.py)
```

脚本如下：
```
export CUDA_VISIBLE_DEVICES=0
export PYTHONPATH=`pwd`/cn_clip

path=/data/datasets
dataset=fgvc-aircraft-2013b-variants102-example
datapath=${path}/datasets/${dataset}/test:data/datasets/fgvc-aircraft-2013b-variants102-example/test
savedir=${path}/save_predictions:data/pretrained_weights
vision_model=ViT-B-16
text_model=RoBERTa-wwm-ext-base-chinese
resume=data/pretrained_weights/clip_cn_vit-b-16.pt
label_file=${path}/${dataset}/label_cn.txt
index=${7:-}

python -u E:/Project/CLIP/Chinese-CLIP-master/cn_clip/eval/zeroshot_evaluation.py \
    --datapath="${datapath}" \
    --label-file=${label_file} \
    --save-dir=${savedir} \
    --dataset=${dataset} \
    --index=${index} \
    --img-batch-size=64 \
    --resume=${resume} \
    --vision-model=${vision_model} \
    --text-model=${text_model}
```

**Comment by yangapku** [comment]
收到，我们先排查一下哈

**Comment by yangapku** [comment]
@zhou-wenn 您好，您可以先按照我们以下给出的建议试一试：

1. 首先尝试`pip uninstall cn_clip`，卸载掉环境中已经安装的`cn_clip`包。因为您已经拉下了我们的完整代码，并且这一部分zero-shot的代码可以不需要pip装`cn_clip`包。直接命令行进入您项目代码的目录`Chinese-CLIP-master`，即可运行这个bash命令。
2. 您在脚本`run_scripts/zeroshot_eval.sh`中，不需要对原始的脚本写法进行改动。需要您指定的配置项，均是执行`bash run_scripts/zeroshot_eval.sh`这个命令时传入的（就是这行bash命令后面的几个参数），它们会传入脚本中替换掉`{1}, {2}, ..., {7}`这些变量，具体您可以再简单熟悉下shell脚本的传参机制。
3. 执行bash命令时，最后一个配置项`${ckpt_path}`需要填写完整的预训练模型pt文件路径，仅仅写`data/ckpt`是不行的哈。

请您先按照这几项建议修改下，如果还有问题请继续留言！

**Comment by zhou-wenn** [comment]
非常感谢作者的回复，给予了我很大的帮助，我会依照上述建议再尝试，谢谢！

**Comment by zhou-wenn** [comment]
作者您好，在您的帮助下zeroshot_eval.sh已成功运行，也成功得到了上述所提到的准确率，非常感谢。
之后想尝试训练模型，但使用训练命令时却没有反应，可以麻烦您解答一下吗？ ${DATAPATH}文件夹命名为data，datasets使用作者提供预处理好的MUGE。
输入命令如下：
`bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh data`
输入后，没有反馈信息
![image](https://user-images.githubusercontent.com/92359626/219132259-57a31c54-8aaa-4fe2-abb0-c7354ec0f2da.png)

脚本设置如下：
`GPUS_PER_NODE=1
WORKER_CNT=1
export MASTER_ADDR=127.0.0.1
export MASTER_PORT=8514
export RANK=0 

export PYTHONPATH=${PYTHONPATH}:`pwd`/cn_clip/

…
`
