### ISSUE TITLE
训练batchsize

### ISSUE THREAD

**Issue by ding1995** [OFA-Sys/Chinese-CLIP#33]
作者你好，请教一下128卡 v100是如何做到训练ViT- L/14时batchsize可以设置为32k的？是使用了fp16么？我实验时用混合精度，batchsize最大为10k，再大就out of menmory了。

**Comment by yangapku** [comment]
您好，您应该是参考了我们技术报告的附录部分哈。和其他规模一样，我们预训练ViT-L/14规模也是分为2个阶段进行。第一个阶段我们冻结视觉侧部分，第二个阶段再解除冻结双塔一起训练。具体来说，正如我们在附录里面具体描述的，第一个阶段，我们是像您说的用128 V100卡，batch开到了32768。在这个阶段，因为视觉侧不进行参数更新，所以反向计算比较少，相比于第二个阶段一起训练双塔，就能节省大量显存。第二个阶段，我们是放开一起训练的，按照附录对应部分所说，当时是128 V100卡，batch相比于一阶段减小到了4608。两个阶段都是混合精度训练的。当时我们还没有加入重计算策略，后面ViT-H/14规模加入并使用上了，这个也可以用一定的时间开销，换取显存占用的减小（参见我们最新的Readme）。

**Comment by yangapku** [comment]
另外补充下，我们的V100是32G显存的卡型哈。

**Comment by ding1995** [comment]
感谢解答！
