### ISSUE TITLE
CLIP for Image Captioning

### ISSUE THREAD

**Issue by yuezih** [OFA-Sys/Chinese-CLIP#34]
非常棒的代码，感觉是目前最贴心最易用的 VLP 代码框架，感谢各位作者耐心的开源工作！不知道作者**有没有计划添加在生成任务（比如 image captioning）上进行微调的代码**，目前中文 VLP 似乎都没有像 BLIP 那样基于 captioning 预训练的，不知道 CN-CLIP 在生成任务上的表现如何，如果有微调代码就再好不过了❤️

**Comment by yangapku** [comment]
同学您好~ 感谢您对于Chinese-CLIP的关注，目前我们的repo暂时还没有支持captioning任务哈。但是看到您之前已经关注了我们的OFA项目，OFA现在不仅支持英文数据集，也已经支持中文多模态任务，并且有了中文预训练ckpt了。在MUGE caption任务的数据集上，中文OFA的表现也不错！ 😄 建议您试用一下，有问题的话可以在OFA repo中向我们提issue

**Comment by yuezih** [comment]
原来如此，感谢提醒！
