### ISSUE TITLE
基于提供的权重，无法复现clip_cn_vit-b-16结果

### ISSUE THREAD

**Issue by Maycbj** [OFA-Sys/Chinese-CLIP#35]
1. 使用你们提供的数据集（Flickr30k-CN）及pretrain权重，运行代码，无法得到预期结果。
{"score": 74.3, "mean_recall": 74.3, "r1": 54.42, "r5": 80.82000000000001, "r10": 87.66000000000001}}
<img width="434" alt="image" src="https://user-images.githubusercontent.com/19340566/209259689-5d4f7b4f-715c-4a4b-a1ea-1f7ad610a7b0.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/19340566/209259632-e1465c76-af4d-4587-bb7d-a4eaf2bd4f6e.png">

启动脚本为：
<img width="640" alt="image" src="https://user-images.githubusercontent.com/19340566/209259764-dcb4b5df-b2ff-479d-a225-145094c5af13.png">

是不是某个超参不对？

**Comment by Maycbj** [comment]
我发现问题了~

**Comment by yangapku** [comment]
您好，请您注意我们readme中的描述哈“_篇幅所限，我们这里给出baseline模型和Chinese-CLIP的**最优规模模型结果**，关于Chinese-CLIP各规模的详细结果指标，请详见[Results.md](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/Results.md)_”。另外说明下，我们汇报的Flickr30K-CN结果为测试集结果，所以按照Readme流程评测并复现时，`split`请取`test`。
