### ISSUE TITLE
Flickr数据使用问题

### ISSUE THREAD

**Issue by Sync-yxh** [OFA-Sys/Chinese-CLIP#36]
请问CN-CLIP是如何使用Flickr数据中一个图片对应的多个文本的，如何避免同一图片的多个文本出现在同一个batch中，成为错误的负样本？谢谢。

**Comment by yangapku** [comment]
您好，我们是直接拆成多个图文对样本处理的，相关具体流程可以参考[readme数据预处理部分](https://github.com/OFA-Sys/Chinese-CLIP#%E6%95%B0%E6%8D%AE%E9%9B%86%E6%A0%BC%E5%BC%8F%E9%A2%84%E5%A4%84%E7%90%86)和[finetune dataset的代码实现](https://github.com/OFA-Sys/Chinese-CLIP/blob/2e450acf811e267fe0508ed506a07c1776c2e3ca/cn_clip/training/data.py#L37)。因为一方面训练的时候全部训练图文对有随机shuffle，另一方面对比学习是在整个大global batch上进行的，所以评估影响应该比较有限，对这一点并没做特殊处理。我们汇报的finetune结果，也是直接用开源代码跑出的，没有专门考虑避免训练batch中一对多的情况。当然您也可以在目前的基础上继续优化数据处理和采样流程，可能会有更好的提升~
