### ISSUE TITLE
RoBERTa-wwm-ext-base-chinese.json文件在?

### ISSUE THREAD

**Issue by PineREN** [OFA-Sys/Chinese-CLIP#4]
ViT-B-16.json文件可以在open-clip下找到，请问这个在哪里能找到？

**Comment by yangapku** [comment]
您好，Chinese-CLIP代码中已经包含了所有目前支持的config，均可以在Chinese-CLIP/src/training/model_configs/下找到

**Comment by yangapku** [comment]
您好，我们刚刚对代码进行了更新，路径名有一些小改动，可以在 Chinese-CLIP/cn_clip/training/model_configs/ 下找到哈

**Comment by PineREN** [comment]
非常感谢您这么迅速的回复。我还有几个问题，希望能得到您的解答
1、我看都需要将图像转化成lmdb格式，能否对单张图像进行处理？数据预处理代码有吗？
2、图片特征提取与原openai提取的差距大吗？是否可以使用您提供的模型提取的文本特征和原clip提取的图像特征库进行检索，我试了后感觉效果一般。
3、能否分享一下ViT-B/32的预训练模型。
再次由衷感谢！

**Comment by yangapku** [comment]
您好，关于问题1，我们已经补充了API快速调用的功能，可以方便处理单张图像了；对于问题2，由于中文CLIP图像侧模型权重，和英文CLIP图像侧权重不同，所以双方的特征是不能相互混用的，您出现的结果是符合预期的，请都使用中文CLIP产出图文特征；对于问题3，我们会持续训练更多规模的预训练模型，请您再耐心等待下
