### ISSUE TITLE
MUGE数据集中图文相关性分数为啥分布在0.3-0.6之间？  

### ISSUE THREAD

**Issue by BlackManLw** [OFA-Sys/Chinese-CLIP#42]
就是用提取的图像和文本向量计算余弦距离  ；尝试了一下实际的数据集好像也存在这个问题

**Comment by yangapku** [comment]
您好，这个应该是正常的情况。图像侧和文本侧的归一化特征，虽然能够产生跨模态的关联，但是在语义空间中还是不会完全对齐在一起的，所以图文特征余弦距离一定不可能到达接近1这样的水平，您也可以用OpenAI CLIP产出的向量，找些英文文本和图像对试验试验。但是，余弦距离之间的相对大小，能够反应图文相似性的高低，这个您可以通过我们的[检索demo](https://www.modelscope.cn/studios/damo/chinese_clip_applications/summary)观察效果（检索结果按照余弦距离排序）。

对于Chinese CLIP计算的相似度，您可以有两种用法。一种情况是考虑相似性的概率分布（比如我们[快速使用API](https://github.com/OFA-Sys/Chinese-CLIP#api%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)中一个图片匹配多个候选文本的情况），您可以参考快速使用API中`model.get_similarity`的计算过程，对余弦距离先乘上`logit_scale.exp()`（做这步乘法是因为我们和OpenAI CLIP一样在训练时考虑temperature，我们预训练模型的`logit_scale.exp()`为100）后在候选项之间做softmax得到概率分布，就可以看到最相关的候选项（比如我们快速使用API示例中的"皮卡丘"文本）相比于其他候选有显著更高的概率。另一种做法，就是考虑根据实际的使用体验，卡一个余弦距离的阈值（或取topk），也能够把相关样本和不相关的区分开。

如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！

**Comment by BlackManLw** [comment]
> 检索结果按照余弦距离排序

但是R2D2的效果就会比较好一些，这是什么原因呢？ 我看该模型比R2D2在图文检索中的指标要更好一些！

**Comment by yangapku** [comment]
我不太了解R2D2的具体实现哈，在同样的数据集中，Chinese-CLIP能够以更简单的结构（不需要排序层，仅仅依靠双塔结构）在多个指标优于R2D2。https://github.com/yuxie11/R2D2/blob/main/r2d2_inference_demo.py#L20 您是参考它这个计算方式吗？这个函数最后输出也是softmax概率（而且是经过了它复杂的排序模块的打分），并不是图文特征内积哈。我理解正常的对比学习训练，从原理上也是无法让图文特征直接得到接近1的余弦相似度的，即使图文匹配性很好。

**Comment by BlackManLw** [comment]
那我想问一下在论文中For the part of data from LAION-5B, we
remove the samples with CLIP scores lower than
0.26 computed by mCLIP (Carlsson et al., 2022). 这个0.26的分数是如何计算出来的呢？ 也是分别提取图像和文本的特征，然后计算两个特征之间的余弦值，然后卡一个阈值筛选吗？

**Comment by yangapku** [comment]
您好，实际上这一步是LAION官方对于非英语数据的处理做法哈，我们是直接使用的LAION所给出的处理好的中文图文，并在文章中复述了他们的预处理做法（LAION官方的blog参见[链接](https://laion.ai/blog/laion-5b/)"CLIP inference at the post-processing stage"部分）。我理解0.26这个分数阈值，就是如您所说的分别提取图像和文本的特征，然后计算两个特征之间的余弦值，然后卡这个阈值筛选的哈。
