### ISSUE TITLE
onnx和tensorrt里为什么要把batch size设为1？无法理解

### ISSUE THREAD

**Issue by huohuade-blog** [OFA-Sys/Chinese-CLIP#47]
就因为方便比较速度吗？建议提供动态的batch_size

**Comment by yangapku** [comment]
我理解现在转换的流程已经非常简单了，如果您比较着急，完全可以转换脚本稍加改动（改一下ONNX输入的shape），就能让它支持非1的batch size。动态的batch_size性能会比fixed batch_size稍有影响，我们采用fixed batch_size，其中使用最灵活的就是batch_size=1，就是这样的考虑哈。后面我们给脚本做几个配置项，加上可指定的fixed batch_size或者动态的batch_size，感谢建议。

如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！

**Comment by huohuade-blog** [comment]
> 我理解现在转换的流程已经非常简单了，如果您比较着急，完全可以转换脚本稍加改动（改一下ONNX输入的shape），就能让它支持非1的batch size。动态的batch_size性能会比fixed batch_size稍有影响，我们采用fixed batch_size，其中使用最灵活的就是batch_size=1，就是这样的考虑哈。后面我们给脚本做几个配置项，加上可指定的fixed batch_size或者动态的batch_size，感谢建议。
> 
> 如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！

 谢谢你的回复。无法动态设置batch_size，导致gpu使用率无法打满。我已经找到需要修改的位置，就是pytorch_to_onnx.py文件的108-109行。希望也帮到后续有相同需求的人。

**Comment by palewithout** [comment]
> 

该咋改呢，只是想做下图像批处理，不是很熟pytorch，方便给个例子吗～

**Comment by palewithout** [comment]
> 



> > 我理解现在转换的流程已经非常简单了，如果您比较着急，完全可以转换脚本稍加改动（改一下ONNX输入的shape），就能让它支持非1的batch size。动态的batch_size性能会比fixed batch_size稍有影响，我们采用fixed batch_size，其中使用最灵活的就是batch_size=1，就是这样的考虑哈。后面我们给脚本做几个配置项，加上可指定的fixed batch_size或者动态的batch_size，感谢建议。
> > 如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！
> 
> 谢谢你的回复。无法动态设置batch_size，导致gpu使用率无法打满。我已经找到需要修改的位置，就是pytorch_to_onnx.py文件的108-109行。希望也帮到后续有相同需求的人。
该咋改呢，只是想做下图像批处理，不是很熟pytorch，方便给个例子吗～

**Comment by zhin2929** [comment]
我也需要这方面的帮助

**Comment by wanghaoran-ucas** [comment]
> 该咋改呢，只是想做下图像批处理，不是很熟pytorch，方便给个例子吗～

dummy_img = Image.new('RGB', (resolution, resolution))
image = torch.stack([preprocess(dummy_img) for _ in range(8)])  # shape: [4, 3, H, W]
text = clip.tokenize([""] * 8, context_length=args.context_length)  # shape: [4, L]
改为想要的batch就行
