### ISSUE TITLE
Huggingface上的ViT-B/16的demo的输出为什么和本地跑的模型输出不一致？

### ISSUE THREAD

**Issue by zhh9211** [OFA-Sys/Chinese-CLIP#48]
用的不是同一套权重么？还是压根就不是同一个模型？表现也差太多了吧

**Comment by yangapku** [comment]
您好，使用的是同一个模型，可以用`torch.load`找到对应的参数看看参数值是否一致。另外我们在HF transformers代码库，也提供了从github到HF的ckpt的[格式转换脚本](https://github.com/huggingface/transformers/blob/main/src/transformers/models/chinese_clip/convert_chinese_clip_original_pytorch_to_hf.py)。我们跑过同样的case，在微小的误差范围内，是可以视为一致的。

如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！

**Comment by songge25** [comment]
脚本要求的json文件在哪呢，我看模型训练之后么有
