### ISSUE TITLE
没有独立显卡的电脑可以使用吗？如果可以的话，需要怎么设置？

### ISSUE THREAD

**Issue by tetejm** [OFA-Sys/Chinese-CLIP#49]
没有独立显卡的电脑（CPU有inter的核显）可以使用吗？如果可以的话，需要怎么设置？

**Comment by yangapku** [comment]
CPU暂时不能训练，但是可以载入模型并提取特征哈，环境需要安装一下CPU版本的pytorch。您可以参考readme中的[快速使用api](https://github.com/OFA-Sys/Chinese-CLIP#api%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)一节，进行特征提取和图文相似度计算。

**Comment by yangapku** [comment]
`device = "cuda" if torch.cuda.is_available() else "cpu"`这一行，就是指定提取特征的设备，如果没有GPU，则`torch.cuda.is_available()`是False，pytorch就会使用CPU进行特征计算了，不过速度肯定是会比GPU慢一些哈。

**Comment by tetejm** [comment]
👌，谢谢！

**Comment by tetejm** [comment]
> `device = "cuda" if torch.cuda.is_available() else "cpu"`这一行，就是指定提取特征的设备，如果没有GPU，则`torch.cuda.is_available()`是False，pytorch就会使用CPU进行特征计算了，不过速度肯定是会比GPU慢一些哈。

👌，谢谢！

**Comment by xyfacai** [comment]
显卡是否有最低要求
