### ISSUE TITLE
请问，提供的预训练模型是否针对图召回文进行预训练过？

### ISSUE THREAD

**Issue by dongZheX** [OFA-Sys/Chinese-CLIP#5]
感谢开源。

请问，提供的预训练模型是否针对图召回文进行预训练？

现在尝试了下在我们数据上进行图召回文 fine-tuning， recall 比较低。
Recall@100	0.23963270260850056

谢谢。

**Comment by dongZheX** [comment]
> 预训练就是用图文pair数据做contrastive learning。能说下数据场景么，以及对比baseline，比如未加预训练、其他预训练模型比如英文CLIP等？

对比的是 我们自己这边训练的一个中文 clip， clip ：recall100:  0.451708。
请问您那边模型里的 loss 是对称的吗

**Comment by JustinLin610** [comment]
是的，和CLIP的一样

**Comment by dongZheX** [comment]
> 是的，和CLIP的一样

ok，了解了，感谢。

**Comment by JustinLin610** [comment]
> > 是的，和CLIP的一样
> 
> ok，了解了，感谢。

客气。

// 不太好判断是模型迁移能力问题，还是训练问题等。如果之后有更详细的信息可以提供的话，也欢迎给我们提供，我们看看怎么改进。
