### ISSUE TITLE
关于训练过程中all_gather的疑问

### ISSUE THREAD

**Issue by robbenplus** [OFA-Sys/Chinese-CLIP#54]
您好，在[train.py](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/cn_clip/training/train.py#L35)的35行到44行，为什么聚合成global_batch的时候要再做一次35行到44行的操作，不可以直接用gathered_image_features和gathered_text_features吗？

我的理解是这样的（单机多卡下），只是顺序不同，但每张卡上的损失是一样的？
![image](https://user-images.githubusercontent.com/48018167/218703674-84d45995-1843-42b5-b2a6-7f6003037a31.png)

**Comment by yangapku** [comment]
您好，这样的写法是直接引用自open_clip的实现哈，我理解主要是需要执行`torch.cat`，把每张卡来的特征拼成tensor（`gathered_image_features`还是个list不是tensor），顺序确实按您所说的也没什么问题哈。

**Comment by robbenplus** [comment]
> 您好，这样的写法是直接引用自open_clip的实现哈，我理解主要是需要执行`torch.cat`，把每张卡来的特征拼成tensor（`gathered_image_features`还是个list不是tensor），顺序确实按您所说的也没什么问题哈。

我印象里CLIP没开源训练代码呀，您能否给一个“open_clip的实现”的链接呢？

**Comment by canornot** [comment]
其实本质原因是因为torch.distributed.all_gather出来的结果gathered_image_features没有梯度，训练的话不能反向传播。所以把image_features拿出来的话打通反向传播了。

你可以试一下all_image_features=torch.cat(gathered_image_features)就会发现报错。

当然顺序是无所谓的
