### ISSUE TITLE
load_from_name代码逻辑有问题

### ISSUE THREAD

**Issue by zyh3826** [OFA-Sys/Chinese-CLIP#56]
load_from_name的[第97行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L97)，如果输入的name参数是模型的本地路径，那么这个name不会出现在_MODEL_INFO中，会报KeyError，而在[第88行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L88)有处理输入的是本地路径的情况

**Comment by yangapku** [comment]
收到，我们看下哈

**Comment by DtYXs** [comment]
> load_from_name的[第97行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L97)，如果输入的name参数是模型的本地路径，那么这个name不会出现在_MODEL_INFO中，会报KeyError，而在[第88行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L88)有处理输入的是本地路径的情况

感谢您指出的问题，在最新的代码增加了针对load本地路径模型的支持。

**Comment by DtYXs** [comment]
> load_from_name的[第97行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L97)，如果输入的name参数是模型的本地路径，那么这个name不会出现在_MODEL_INFO中，会报KeyError，而在[第88行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L88)有处理输入的是本地路径的情况

感谢您指出的问题，最新的代码增加了对load本地路径模型的支持。在输入为本地模型路径时，需要额外输入对应的vision_model_name，text_model_name，以及input_resolution。例如load本地的Base规模Chinese-CLIP模型：
`load_from_name(name={local_base_model_path}, device={device}, vision_model_name="ViT-B-16", text_model_name="RoBERTa-wwm-ext-base-chinese", input_resolution=224)`

**Comment by zyh3826** [comment]
> > load_from_name的[第97行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L97)，如果输入的name参数是模型的本地路径，那么这个name不会出现在_MODEL_INFO中，会报KeyError，而在[第88行](https://github.com/OFA-Sys/Chinese-CLIP/blob/2c586c5efdc63210eb03272a32a292ea85b727b7/cn_clip/clip/utils.py#L88)有处理输入的是本地路径的情况
> 
> 感谢您指出的问题，最新的代码增加了对load本地路径模型的支持。在输入为本地模型路径时，需要额外输入对应的vision_model_name，text_model_name，以及input_resolution。例如load本地的Base规模Chinese-CLIP模型： `load_from_name(name={local_base_model_path}, device={device}, vision_model_name="ViT-B-16", text_model_name="RoBERTa-wwm-ext-base-chinese", input_resolution=224)`

感谢您的及时处理
