### ISSUE TITLE
运行训练脚本没跑起来

### ISSUE THREAD

**Issue by zhou-wenn** [OFA-Sys/Chinese-CLIP#57]
作者您好，在您的帮助下前一个问题zeroshot_eval.sh已成功运行，也成功得到了您所提到的准确率，非常感谢。
之后想尝试训练模型，但使用训练命令时却没有反应，可以麻烦您解答一下吗？ 
${DATAPATH}文件夹命名为data，datasets使用作者提供预处理好的MUGE。

输入命令如下：
bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh data
输入后，没有反馈信息
![219132259-57a31c54-8aaa-4fe2-abb0-c7354ec0f2da](https://user-images.githubusercontent.com/92359626/220244447-6ed324e5-906f-44fb-8cd4-0bc36d9866f7.png)

脚本设置如下：
```

GPUS_PER_NODE=1
WORKER_CNT=1
export MASTER_ADDR=localhost
export MASTER_PORT=8514
export RANK=0 

export PYTHONPATH=${PYTHONPATH}:`pwd`/cn_clip/

…
```
脚本后面部分没有改动

**Comment by DtYXs** [comment]
您好，您可以尝试下将sh脚本中第59行`python3 -m torch.distributed.launch ...`中的`python3`改为`python`再试一下看看

**Comment by zhou-wenn** [comment]
谢谢作者，改为python后可以运行了，运行后反馈了新的错误，信息如下，是windows系统的问题吗？
```
Prophet@DESKTOP-32QKO81 MINGW64 /d/PyCharm/PycharmProjects/CLIP/Chinese-CLIP-master
$ bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh data

NOTE: Redirects are currently not supported in Windows or MacOs.
D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "cn_clip/training/main.py", line 284, in <module>
    main()
  File "cn_clip/training/main.py", line 54, in main
    dist.init_process_group(backend="nccl")
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 727, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2516) of binary: D:\Anaconda\envs\PyTorch\python.exe
Traceback (most recent call last):
  File "D:\Anaconda\envs\PyTorch\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\PyTorch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\run.py", line 752, in run
    elastic_launch(
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
cn_clip/training/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-22_01:24:42
  host      : DESKTOP-32QKO81
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2516)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by DtYXs** [comment]
> 谢谢作者，改为python后可以运行了，运行后反馈了新的错误，信息如下，是windows系统的问题吗？
> 
> ```
> Prophet@DESKTOP-32QKO81 MINGW64 /d/PyCharm/PycharmProjects/CLIP/Chinese-CLIP-master
> $ bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh data
> 
> NOTE: Redirects are currently not supported in Windows or MacOs.
> D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torchrun.
> Note that --use_env is set by default in torchrun.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See
> https://pytorch.org/docs/stable/distributed.html#launch-utility for
> further instructions
> 
>   warnings.warn(
> Traceback (most recent call last):
>   File "cn_clip/training/main.py", line 284, in <module>
>     main()
>   File "cn_clip/training/main.py", line 54, in main
>     dist.init_process_group(backend="nccl")
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 602, in init_process_group
>     default_pg = _new_process_group_helper(
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\distributed_c10d.py", line 727, in _new_process_group_helper
>     raise RuntimeError("Distributed package doesn't have NCCL " "built in")
> RuntimeError: Distributed package doesn't have NCCL built in
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2516) of binary: D:\Anaconda\envs\PyTorch\python.exe
> Traceback (most recent call last):
>   File "D:\Anaconda\envs\PyTorch\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\Anaconda\envs\PyTorch\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
>     main()
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py", line 189, in main
>     launch(args)
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launch.py", line 174, in launch
>     run(args)
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\run.py", line 752, in run
>     elastic_launch(
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "D:\Anaconda\envs\PyTorch\lib\site-packages\torch\distributed\launcher\api.py", line 245, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ============================================================
> cn_clip/training/main.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-02-22_01:24:42
>   host      : DESKTOP-32QKO81
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 2516)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

您好，似乎是由于Windows系统不支持NCCL分布式后端。可以尝试将`cn_clip/training/main.py`中第55行`dist.init_process_group(backend="nccl")`改为`dist.init_process_group(backend="gloo")`，但不保证可以正常训练。建议在Linux系统上进行训练。
可以参考Pytorch文档https://pytorch.org/docs/stable/distributed.html

**Comment by John-Kieron** [comment]
我使用的是linux ubuntu22.04.1LTS版本也遇到上了上述问题，为什么呢？

**Comment by DtYXs** [comment]
> 我使用的是linux ubuntu22.04.1LTS版本也遇到上了上述问题，为什么呢？

您好，您能具体描述一下您遇到的问题吗
