### ISSUE TITLE
onnx bert model attention_mask

### ISSUE THREAD

**Issue by qiankl** [OFA-Sys/Chinese-CLIP#66]
Hi, I am trying to convert bert model to onnx format and I followed the instruction in 'deployment.md'. Everything is good.

However, I find the results of onnx and pytorch are different, as attention_mask is one of inputs in pytorch but onnx not. The similarity of text features are around ~0.8.

Is it a bug or intended? Will it affact a lot if attention_mask is not used?

**Comment by yangapku** [comment]
Thank you for pointing out the issue. Let us have a check!

**Comment by qiankl** [comment]
I am sorry that I did not check the results carefully. This problem is caused by mnn model, not onnx. Sorry for the inconvenience.
