### ISSUE TITLE
pillow版本问题

### ISSUE THREAD

**Issue by huangyangke** [OFA-Sys/Chinese-CLIP#71]
我在调用预处理方法的时候注意到不同的Image版本读取压缩图片如（.jpg\.jpeg)，会有点区别，导致模型输出有点波动。为了能达到最好的使用效果，我想请问下您在训练时使用的pillow版本。

**Comment by DtYXs** [comment]
您好，您可以尝试下9.0.1版本的pillow，部分的finetune实验可能在更高的版本（如9.2.0）上进行的，供您参考
