### ISSUE TITLE
报错main.py: error: unrecognized arguments: --local-rank=0

### ISSUE THREAD

**Issue by 1026468976** [OFA-Sys/Chinese-CLIP#74]
你好！我电脑只有一个GPU，我就把相应参数改成了单机单卡的训练方式，但是报错main.py: error: unrecognized arguments: --local-rank=0，请问这该如何解决？

**Comment by DtYXs** [comment]
您好，判断您可能是想自己手动传入`local_rank`参数，您可以尝试将传递的参数改为`--local_rank=0`再试一下。

**Comment by shilida** [comment]
> 你好！我电脑只有一个GPU，我就把相应参数改成了单机单卡的训练方式，但是报错main.py: error: unrecognized arguments: --local-rank=0，请问这该如何解决？

您好，我也碰到这个问题了，请问你是如何解决的呢？

**Comment by DtYXs** [comment]
> > 你好！我电脑只有一个GPU，我就把相应参数改成了单机单卡的训练方式，但是报错main.py: error: unrecognized arguments: --local-rank=0，请问这该如何解决？
> 
> 您好，我也碰到这个问题了，请问你是如何解决的呢？

您好，请问可以提供一下您具体的训练脚本吗

**Comment by 1026468976** [comment]
您好，我并没有手动传入local_rank参数，最后这个问题还是没有解决

**Comment by 1026468976** [comment]
您好，那边回复的是可能传入了参数--local-rank，修改一下就可以了。但是我其实并没有自己传入这个参数，最后我并没有解决这个问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 晚上7:44
***@***.***&gt;;
抄送:&nbsp;"HUANG ***@***.******@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] 报错main.py: error: unrecognized arguments: --local-rank=0 (Issue #74)





   
你好！我电脑只有一个GPU，我就把相应参数改成了单机单卡的训练方式，但是报错main.py: error: unrecognized arguments: --local-rank=0，请问这该如何解决？
  
您好，我也碰到这个问题了，请问你是如何解决的呢？
  
您好，请问可以提供一下您具体的训练脚本吗

**Comment by shilida** [comment]
> 
我解决了这个问题，把脚本中的python3 -m torch.distributed.launch  换成  torchrun就可以了

**Comment by 1026468976** [comment]
非常感谢您的帮助！也许您可以在GitHub上分享您的解决方法，这将帮助到许多人（ღ( ´･ᴗ･` )比心）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OFA-Sys/Chinese-CLIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 晚上7:48
***@***.***&gt;;
抄送:&nbsp;"HUANG ***@***.******@***.***&gt;;
主题:&nbsp;Re: [OFA-Sys/Chinese-CLIP] 报错main.py: error: unrecognized arguments: --local-rank=0 (Issue #74)





   
我解决了这个问题，把脚本中的python3 -m torch.distributed.launch  换成  torchrun就可以了
