### ISSUE TITLE
No module named 'torch._C._distributed_rpc'; 'torch._C' is not a packageModuleNotFoundError

### ISSUE THREAD

**Issue by yourfathermyson** [OFA-Sys/Chinese-CLIP#75]
请问微调代码可以在Windows操作系统上实现么？我在Windows操作系统上调试的时候出现torch的问题，这是因为linux和Windows上torch有差别的原因么？

**Comment by DtYXs** [comment]
您好，建议您可以先检查一下代码目录中是否有命名为`torch`的同名文件夹，以及检查一下是否安装了正确的GPU版本的Pytorch。建议您在Linux系统训练，在Windows系统训练可能会出现问题，您可以参考https://github.com/OFA-Sys/Chinese-CLIP/issues/57#issuecomment-1439787723
