### ISSUE TITLE
About COCO-CN dataset, how should I process it?

### ISSUE THREAD

**Issue by Suncheng2022** [OFA-Sys/Chinese-CLIP#76]
I have applied successfully, and it contains some Chinese sentences marks. How should I handle the COCO-CN dataset, do I write a script code based on the introduction of your project?
我已经申请成功，下载内容包含一些中文标注。我应该如何处理COCO-CN数据集呢，按照您项目的介绍自己写脚本编码序列化吗？

**Comment by yangapku** [comment]
您好，您可以邮件联系我们，我们可以为您提供处理好的LMDB格式数据集。

**Comment by Suncheng2022** [comment]
已收到，非常感谢！
