### ISSUE TITLE
零样本分类结果

### ISSUE THREAD

**Issue by pandaupc** [OFA-Sys/Chinese-CLIP#77]
你好，我使用CN_CLIP VIT-H/14 模型去进行零样本分类，在CIFAR10，CIFAR100，DTD，EuroSAT，FER，FGVC，MNIST上取得了与项目公布的相同结果，但在KITTI 和 PC 数据集上，结果显著变差，是什么原因呢？（评估脚本和数据都是按照该项目中的），kitti-distance 只有16.46，PC 位50.12。希望帮忙解答，谢谢！

**Comment by pandaupc** [comment]
另外我在你们方法的基础上，做了一些改进，在zero-shot image classification 上准确率有比较大的提升，除了kitti-distance 和 PC （使用你们的脚本和数据无法复现你们的结果，在这我的实验中，我提出的方法相对报告的结果，也有显著提升），新的改进都能对之前的结果在R1 上有0.3%- 1.8%的提升，其中PC上准确率可以达到 59.0 ，比你们报告的52.4 ，结果提升6.6个点，这个改进与当前其他改进方法是正交的，希望能够有进一步沟通

**Comment by DtYXs** [comment]
> 你好，我使用CN_CLIP VIT-H/14 模型去进行零样本分类，在CIFAR10，CIFAR100，DTD，EuroSAT，FER，FGVC，MNIST上取得了与项目公布的相同结果，但在KITTI 和 PC 数据集上，结果显著变差，是什么原因呢？（评估脚本和数据都是按照该项目中的），kitti-distance 只有16.46，PC 位50.12。希望帮忙解答，谢谢！

您好，收到您的问题，我们这边看一下哈

**Comment by DtYXs** [comment]
> 另外我在你们方法的基础上，做了一些改进，在zero-shot image classification 上准确率有比较大的提升，除了kitti-distance 和 PC （使用你们的脚本和数据无法复现你们的结果，在这我的实验中，我提出的方法相对报告的结果，也有显著提升），新的改进都能对之前的结果在R1 上有0.3%- 1.8%的提升，其中PC上准确率可以达到 59.0 ，比你们报告的52.4 ，结果提升6.6个点，这个改进与当前其他改进方法是正交的，希望能够有进一步沟通

您好，您可以先准备一份pull request进行提交，我们进行一下review

**Comment by pandaupc** [comment]
好的，我提交一下我实验结果，你们先review下。

我认为我的方法在这种基于prompt进行的分类、检测等任务上都应该有一致的提升。

**Comment by pandaupc** [comment]
已提交结果对比，请review，谢谢！
