### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by diyiiyiii** [OFA-Sys/Chinese-CLIP#8]
感谢您的分享！我想请问一下，训练的（~2亿图文对）是从网站上随机爬取的嘛？有数据筛选环节嘛？是否包含了一些公开的caption数据集？期待您的回复

**Comment by yangapku** [comment]
您好，关于您关心的数据集相关问题，我们在技术报告论文中已经给出了比较详尽的说明哈。论文链接：https://arxiv.org/pdf/2211.01335.pdf

**Comment by diyiiyiii** [comment]
谢谢啦！

**Comment by yangapku** [comment]
@ywdong 您好，感谢您对我们工作的关注！目前我们暂时还不提供2亿图片直接打包下载的方式，这部分数据主体（~1.8亿）是[Wukong](https://wukong-dataset.github.io/wukong-dataset/download.html)和[LAION-5B中文部分](https://laion.ai/blog/laion-5b/)两个公开数据集组成，都已经是可根据图片url公开下载的，推荐使用LAION官方人员提供的[img2dataset开源工具](https://github.com/rom1504/img2dataset)下载即可，我们也是使用了这个工具，效率很高。直接将这些图片打包提供，可能也会涉及原数据集和原始图片的版权问题。希望理解\~

**Comment by liaoxijuneu** [comment]
你好，感谢分享开源中文模型。想问下wukong和VG数据应用细节：1、wukong数据把训练集和测试集数据都加入训练了吗？ 2、VG数据的应用方式是把box对应的区域&文本作为输入，还是整图&文本作为数据？

**Comment by yangapku** [comment]
@liaoxijuneu 您好，感谢对于我们工作的认可！关于Wukong数据，我们只使用了训练集，没有加入其测试集。关于VG机翻数据，我们是将一张图的区域描述文本（机翻版本）拼接在一起，与整图作为一个图文对。VG这部分数据量级，相比于Wukong和LAION两个来源比例是非常小的。
