### ISSUE TITLE
Flickr30k-CN text2image结果

### ISSUE THREAD

**Issue by pandaupc** [OFA-Sys/Chinese-CLIP#80]
text2image retrival 任务上,MUGE重现了结果，但Flickr30k-CN结果显著小于报告值。我看到之前相关的issue中提到可能是context_length 问题，但我看新的脚本已经修改为52，是什么原因呢？

**Comment by randomtutu** [comment]
> text2image retrival 任务上,MUGE重现了结果，但Flickr30k-CN结果显著小于报告值。我看到之前相关的issue中提到可能是context_length 问题，但我看新的脚本已经修改为52，是什么原因呢？

你好，你那边有进展吗，我这里也有这个问题，改一下context length就可以？
