### ISSUE TITLE
预训练时，是否有使用任何“预”预训练模型？

### ISSUE THREAD

**Issue by Tramac** [OFA-Sys/Chinese-CLIP#81]
看到 [load](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/cn_clip/training/main.py#L99) 代码部分，好奇有个问题：

```
load(model, clip_path=args.clip_weight_path, bert_path=args.bert_weight_path, use_flash_attention=args.use_flash_attention)
```

在 2亿图文对上进行预训练时，是有使用某些 clip_weight 或 bert_weight 做初始化，还是完全 from scratch 的呢？

或者说，预训练时 args.clip_weight_path 与 args.bert_weight_path 是否都为 None 呢。

**Comment by yangapku** [comment]
您好，关于我们每个规模下，对比学习预训练初始化的细节，请参见我们的论文哈，有非常详尽的介绍。

**Comment by Tramac** [comment]
看了一下论文中的介绍，确实非常清晰，赞

**Comment by Tramac** [comment]
看了下论文中的介绍，非常详细、清晰，赞！

自答一下，vision部分使用官方 CLIP image encoder做初始化，text 部分使用 RoBERTa-wwm-ext 做初始化，训练时分两个阶段：
- 先将 image encoder freeze 住，只训 text encoder，有点先弥补中文和英文之间 gap 的意思；
- 打开 image encoder，同时训练，将两者更充分的拉到同一个 domain；
