### ISSUE TITLE
你好，上周与你们沟通后，提交了我做的在zero-shot上的结果，你们最近是否有分析，希望能有进一步交流

### ISSUE THREAD

**Issue by pandaupc** [OFA-Sys/Chinese-CLIP#84]

**Comment by pandaupc** [comment]
希望能够一起合作在更多的任务上进行实验，并发表论文，另外我最近也在找相关工作，希望能有机会一起合作。

**Comment by yangapku** [comment]
收到，我们会尽快完成review哈！如果对我们团队感兴趣，可以将简历邮件投递我们进一步联系~

**Comment by pandaupc** [comment]
如何投递呢？有岗位链接吗？

**Comment by pandaupc** [comment]
你好，周一我通过邮件将简历发给了您，不知道有没有收到，如果收到了，希望能得到您的回复，谢谢！
