### ISSUE TITLE
使用 fp16 进行 finetune 时，精度不符合预期

### ISSUE THREAD

**Issue by Tramac** [OFA-Sys/Chinese-CLIP#85]
预训练模型使用的是 `clip_cn_vit-b-16.pt`

- 使用混合精度或者 fp32 在 Flickr30k-CN 数据上进行 finetune 时，效果正常，部分 log 如下：

<img width="755" alt="image" src="https://user-images.githubusercontent.com/22740819/231665896-b1e23c71-90fd-4e07-b292-8c0e3b7b21ff.png">

- 使用 fp16 在 Flickr30k-CN 数据上进行 finetune 时，Acc 迅速下降至很低的值，log 如下：

<img width="754" alt="image" src="https://user-images.githubusercontent.com/22740819/231666479-58d48be2-0c85-4cd0-b839-17258eb4e513.png">

3 个 epoch 后 acc 也是很低，loss 值几乎没有变化：
<img width="752" alt="image" src="https://user-images.githubusercontent.com/22740819/231667093-916ef30c-9e97-4d77-a3c4-a82011b8e281.png">

可能是什么原因造成的呢？

**Comment by DtYXs** [comment]
您好，初步判断可能是由于使用fp16训练时，较低的数值精度可能导致数值不稳定性问题，对学习率等超参更为敏感。并且由于您的batchsize相对来说比较小，建议您可以尝试降低一下学习率，增大一下warmup，调整合适后fp16应该可以正常训练，也更建议您在更稳定的混合精度模式下进行训练。
