### ISSUE TITLE
少样本 finetune

### ISSUE THREAD

**Issue by raymond1123** [OFA-Sys/Chinese-CLIP#86]
您好，我要对一些缺陷类别进行微调，但是有些类别数据很少，不知道 chinese-clip 对少样本微调的效果如何

**Comment by DtYXs** [comment]
您好，我们下游跨模态检索实验中数据规模最小的为COCO-CN数据集，大约有18k训练样本，目前暂时没尝试过更小规模的数据微调的表现。建议您可以尝试一些数据扩充方法对少类别数据进行补充，对类别较多的数据进行欠采样来进行平衡，或者采用如focal loss等方法来尝试提升在少样本类别上的表现。

**Comment by raymond1123** [comment]
多谢，我会做一些实验试试
