### ISSUE TITLE
单个图片和单个文本计算的相似性是一个30+左右的数值，如何判断是否相关呢

### ISSUE THREAD

**Issue by yier2333** [OFA-Sys/Chinese-CLIP#89]
是否有一个经验阈值T，当一个文本和一个图像的相似性logit得分大于T时是相关的。
多个文本和一个图片可以使用归一化求max，但是单个的情况怎么判断啊

**Comment by yangapku** [comment]
您好，这个确实没有固定标准，余弦相似度您可以根据实际情况，卡一个阈值，比如0.3这样。
