### ISSUE TITLE
关于文本表征的token疑问

### ISSUE THREAD

**Issue by ygfrancois** [OFA-Sys/Chinese-CLIP#92]
你们好，我注意到，paper里写“The top-level feature at the [EOS] position from Transformer is treated as the text representation.” ，但是代码里看起来是放在首位的[CLS] token，这里是不是有点问题？

**Comment by yangapku** [comment]
您好，可能是有一些误解哈。您所指出的部分，是文章"2.1 Preliminaries"小节，这部分主要是介绍原版CLIP的信息作为背景。关于Chinese-CLIP，确实是如您所说，以[CLS]位置的输出特征用于后续计算的。

可能确实会造成一些困惑，所以我们会在近期（投稿结束后）更新我们新的一版技术报告论文到arxiv哈，这一小节我们会去掉了。

**Comment by chenminupup** [comment]
你好，想问下：支持多长文本的输入呢，多少token
