### ISSUE TITLE
请问两阶段有效性验证的曲线图下面的200B-1000B代表什么意思？

### ISSUE THREAD

**Issue by ZYX511** [OFA-Sys/Chinese-CLIP#93]
您好，请问两阶段有效性验证的曲线图下面的200B-1000B代表什么意思？

按照我自己的理解，两阶段有效性验证的曲线图下面的200B-1000B of image-text pairs pretrained，有两个意思
1、是指模型训练过程中遍历的图文对数量200 Billion，论文中提到训练数据量是200M的中文图文对，200B意味着预训练模型经过了1000个epoch，然而clip_ViT-B预训练才59epoch，这不合理

2、 B 指的是 Batch ,按照第一阶段的 batchsize 大小32768，一个 epoch 训练6103个 batch ，那1000B的预训练不足1个epoch，也不合理

我看遍了论文也没有看到关于这个200B~1000B的解释，还请详细告知

**Comment by yangapku** [comment]
您好，已经邮件联系您了哈~ 确实是我们的结果图横轴数量单位画错了，我们会在投稿结束后，尽快完成arxiv论文版本的更新！
