### ISSUE TITLE
Chinese-CLIP是如何修改context length的？How does Chinese-CLIP change the context length?

### ISSUE THREAD

**Issue by DengXianqi** [OFA-Sys/Chinese-CLIP#95]
我看到cn-clip是能够修改tokenizer的context length，但是我没有找到相关的代码是如何实现这个的。

在clip中，tokenizer的max context length为77，因为text-encoder在训练的时候就是如此。所以我想问一下，cn-clip是如何做到的呢？具体的代码又是在哪？

I see that cn-clip is able to modify the context length of the tokenizer, but I can't find the relevant code to implement this.

In clip, the tokenizer has a max context length of 77, because the text-encoder does this when training. So I would like to ask, how does cn-clip do it? Where is the code?

**Comment by kerkathy** [comment]
hi, I'm also wondering on this question. Do you have an answer already?

**Comment by DengXianqi** [comment]
> hi, I'm also wondering on this question. Do you have an answer already?

If the text exceeds the length limit, the tokenizers do not have any processing capability and instead return an AssertionError. Additionally, if you attempt to set a new context length that exceeds 77, which is beyond the input size of the clip, an error will be raised. 
So we need to explore alternative approaches to address this issue.
