### ISSUE TITLE
bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh ${DATAPATH}时出错

### ISSUE THREAD

**Issue by duyz1234** [OFA-Sys/Chinese-CLIP#97]
您好：
         我在尝试bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh [${DATAPATH}时出错，具体问题如下
<img width="681" alt="d20d003c08b05806cd4beedf4c7f0cf" src="https://user-images.githubusercontent.com/132811872/236667013-66dfc533-f106-402a-bcaf-cf4648d4ec73.png">
这样的话，我该如何解决？

**Comment by yangapku** [comment]
您好，请问是否方便给出完整的运行命令和完整报错，方便我们进行归因哈

**Comment by duyz1234** [comment]
非常感谢您的回复。完整的运行命令如下：bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh [${DATAPATH}
以下是完整的报错：
<img width="1053" alt="0da9b16e558849a10516b575870d5f8" src="https://user-images.githubusercontent.com/132811872/236667420-ba7527f2-dcf1-4585-97f7-a56305c41734.png">

**Comment by yangapku** [comment]
好的，再请问您一下pytorch版本是2.0吗，也许您可以参考下issue #94 我们同学最新的回复哈

**Comment by duyz1234** [comment]
以参考，但是还是一样的报错！

**Comment by duyz1234** [comment]
您好，参考下issue 94并已修改，但是还是有问题。
<img width="1054" alt="1e27e011150245575e37dc99f9dffad" src="https://user-images.githubusercontent.com/132811872/236677042-0fef7ac9-4d5d-44b7-8344-4d59371e0748.png">
报错是找不到data，但是我可以cd到dada/train

**Comment by duyz1234** [comment]
您好，参考issue 94并已修改，但是还是有问题。
<img width="1054" alt="1e27e011150245575e37dc99f9dffad" src="https://user-images.githubusercontent.com/132811872/236677233-f7f60194-0486-4cf5-8d70-7aea2a44a145.png">
报错是找不到/raid/home/duyu/Clip/chinese/Chinese-CLIP/DATAPATH/datasets/MUGE/lmdb/train
，但是我可以cd到/raid/home/duyu/Clip/chinese/Chinese-CLIP/DATAPATH/datasets/MUGE/lmdb/train

**Comment by duyz1234** [comment]
下载的数据集如下：
<img width="676" alt="b96eac0b9f70c173a9716bb65a68117" src="https://user-images.githubusercontent.com/132811872/236677946-258eb0a9-e6b4-4820-94d9-47fb37f93581.png">

**Comment by DtYXs** [comment]
您好，请问您方便提供您修改后的训练脚本的完整内容吗？另外，我们也将会更新适配Pytorch2.0版本的脚本，欢迎您之后进行使用

**Comment by duyz1234** [comment]
好的，谢谢您！下面是训练脚本的内容：
<img width="772" alt="805b5321690561f29ac599089746852" src="https://user-images.githubusercontent.com/132811872/236712868-8e474125-31f0-4858-8c2d-73e3349f22b7.png">

**Comment by duyz1234** [comment]
> 好的，谢谢您！下面是训练脚本的内容： <img alt="805b5321690561f29ac599089746852" width="772" src="https://user-images.githubusercontent.com/132811872/236712868-8e474125-31f0-4858-8c2d-73e3349f22b7.png">

![Uploading c96e96b308554e43bf2ac0d7a3dda7a.png…]()

**Comment by duyz1234** [comment]
好的，谢谢您！下面是训练脚本的内容：
![Uploading 805b5321690561f29ac599089746852.png…]()
<img width="755" alt="c96e96b308554e43bf2ac0d7a3dda7a" src="https://user-images.githubusercontent.com/132811872/236714435-e7e40d60-254d-4ebc-b4f1-f03ea3dcea2b.png">

**Comment by duyz1234** [comment]
好的，谢谢您！下面这是我用的训练脚本！
<img width="772" alt="805b5321690561f29ac599089746852" src="https://user-images.githubusercontent.com/132811872/236714707-d52ff57f-1636-450c-905d-0a3a02a22224.png">
<img width="755" alt="c96e96b308554e43bf2ac0d7a3dda7a" src="https://user-images.githubusercontent.com/132811872/236714731-4bf692e6-f9c5-44b4-936c-e0eabaa0f254.png">

**Comment by duyz1234** [comment]
一直提示找不到：/raid/home/duyu/Clip/chinese/Chinese-CLIP/DATAPATH/datasets/MUGE/lmdb/train

**Comment by duyz1234** [comment]
此外，将pytorch版本改为1.10
但是还是一直提示找不到：/raid/home/duyu/Clip/chinese/Chinese-CLIP/DATAPATH/datasets/MUGE/lmdb/train

**Comment by duyz1234** [comment]
您好！我这边又出现了新的问题，麻烦您看一下。
<img width="1078" alt="ab83fe9aab213dd819bc26afdc30449" src="https://user-images.githubusercontent.com/132811872/236728051-4fc050f3-fa90-4a4a-8b77-11d861b20ce9.png">

**Comment by yangapku** [comment]
您好，请参考issue https://github.com/OFA-Sys/Chinese-CLIP/issues/98 中我们同学的回复，`MASTER_ADDR`改为`localhost`，`MASTER_PORT`改为其他端口例如`8514`（如果同一个机器跑多个任务，请分别设置不同的端口号），试试看哈。主要还是`MASTER_ADDR`的问题，本机训练按照sh脚本的注释，应该写为`localhost`或`127.0.0.1`，不是机器的外网ip

**Comment by duyz1234** [comment]
本机训练按照sh脚本的注释，写为localhost后执行还是一样的报错
<img width="1054" alt="04dbf5f278f4c66919835a62d65ba3e" src="https://user-images.githubusercontent.com/132811872/236759483-2b6f9514-07f4-4135-a1df-01855d519f6e.png">

**Comment by yangapku** [comment]
您方便再贴一下当前最新实际运行的脚本吗？

**Comment by duyz1234** [comment]
您好！
这是实际的运行脚本：
<img width="728" alt="6aa52f11f3413a719a399ea37e0b6b9" src="https://user-images.githubusercontent.com/132811872/236764629-3f16336a-1c6a-4a7a-8864-a1d95dd7e5a0.png">
<img width="658" alt="252f96a6325c2ab27cc95b8060820a1" src="https://user-images.githubusercontent.com/132811872/236764672-8b7dddea-719e-4e17-9046-10cc846f66a5.png">
<img width="604" alt="caa4e2ef2ae501729a0c491c2f8b7bd" src="https://user-images.githubusercontent.com/132811872/236764726-51a9c837-67c6-475e-8eda-d5fd23e54057.png">

**Comment by yangapku** [comment]
您好，看到您`RANK`写的是1，请问是多机运行吗？如果是单机，请按照注释，将`RANK`设置为0哈

**Comment by duyz1234** [comment]
收到！谢谢您！我这边是单机运行。按照注释，将RANK设置为0后，出现如下报错
<img width="1049" alt="a0997e294428fe5fae9ade48be7ef1d" src="https://user-images.githubusercontent.com/132811872/236768124-8d0180aa-cbc3-4acd-804a-fda0f1ad23c8.png">

**Comment by yangapku** [comment]
您好，爆显存了，可以尝试缩小batch size试试。另外，方便的话您可以运行nvidia-smi贴一下截图，便于我们了解您显存的情况。

**Comment by yangapku** [comment]
可以的，您可以在命令行下，指定`export CUDA_VISIBLE_DEVICES=X`（`X`为GPU卡编号，如1），指定只使用1号卡。另外，看到您脚本里面，机器显卡数`GPUS_PER_NODE`指定为8，如果是单卡，请根据实际情况指定为1哈。

**Comment by duyz1234** [comment]
我加入export CUDA_VISIBLE_DEVICES=X后还是有问题，具体脚本yij以及如下：
<img width="787" alt="b0dd2bf4e70dcaa602e2cf5cc1ccd9c" src="https://user-images.githubusercontent.com/132811872/236781070-7405c481-2428-4c40-bc8f-e493b975b67e.png">

<img width="716" alt="be84e85447cf8c48f57850e8dd6361a" src="https://user-images.githubusercontent.com/132811872/236781156-719022a8-b762-4a22-8e1d-16614d77da50.png">


<img width="1080" alt="813220f7d044d73d88051260a1c9a73" src="https://user-images.githubusercontent.com/132811872/236781205-5745c1b5-0b85-402a-a067-80f5e9df8527.png">

**Comment by duyz1234** [comment]
非常感谢您，问题已解决！这样应该是正常训练了吧
<img width="1066" alt="b9404e6d3d0d08c56e0313471db96bd" src="https://user-images.githubusercontent.com/132811872/236783116-df6dc9ee-b225-4002-80e5-337fea1b40f3.png">

**Comment by yangapku** [comment]
您好，看起来训练已经可以跑起来了，不过看上去loss比较高（可以确认下是否预训练模型参数有正常load），另外batch size目前开的比较小，可以通过readme里面提到的重计算策略进一步扩大。

您也可以参考运行我们在readme提供的MUGE数据集finetune的jupyter notebook，尝试在MUGE数据集快速得到一组还不错的结果，并在此基础上继续进行优化。

如果有更多问题，欢迎继续留言。如果觉得Chinese-CLIP代码库对您有帮助，请您为我们点点star⭐️并推荐给身边的朋友们！

**Comment by duyz1234** [comment]
感谢您的帮助！我目前有一个疑问，能不能自己造一些图片
样本，比如.png的格式，能否直接改成您这边的数据集要求格式，当做训练集重新训练模型？

**Comment by yangapku** [comment]
您好，当然是可以的。如果使用自己的数据集，请您参考"教程-跨模态检索-准备工作-数据集格式预处理"部分，把自己的原始图片-文本对数据转成最终使用的LMDB格式。

**Comment by DengyingFu** [comment]
> 收到！谢谢您！我这边是单机运行。按照注释，将RANK设置为0后，出现如下报错 <img alt="a0997e294428fe5fae9ade48be7ef1d" width="1049" src="https://user-images.githubusercontent.com/132811872/236768124-8d0180aa-cbc3-4acd-804a-fda0f1ad23c8.png">

请问这个怎么解决的呢，我指定了显卡0（10GB的），但是我观察显卡占用才3MiB，和你这个报错一样

**Comment by hito-Chen** [comment]
> 好的，再请问您一下pytorch版本是2.0吗，也许您可以参考下issue [#94](https://github.com/OFA-Sys/Chinese-CLIP/issues/94) 我们同学最新的回复哈

老师你好，我这边已经按照这位同学的修改，但是还是一样的报错
运行脚本：
![Image](https://github.com/user-attachments/assets/a52f7bad-deef-4519-9737-4e1445fb9d9c)
![Image](https://github.com/user-attachments/assets/ca53fca8-3c0d-4857-a111-1e532866c6c3)
报错：
![Image](https://github.com/user-attachments/assets/140508bb-6218-4a4b-941c-5257a007e27c)

麻烦抽空帮我看看怎么解决，十分感激！
