### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Sally6651** [OFA-Sys/Chinese-CLIP#98]
bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh ${DATAPATH}
您好，请问运行这个会报错怎么解决呢？

**Comment by Sally6651** [comment]
和楼上的情况一样，请问具体的解决办法是什么

**Comment by yangapku** [comment]
您好，还是麻烦您提供下环境细节（CUDA版本、pytorch版本），粘贴下具体的运行命令（请注意根据readme把`${DATAPATH}`替换成实际路径），并给下报错日志，这样可以便于我们尽快看下哈

**Comment by yangapku** [comment]
如果方便的话，也麻烦给一下按照readme的教程（"请在运行前，先根据脚本开头的指引注释，填写好分布式相关配置"），填写好分布式配置后的run_scripts/muge_finetune_vit-b-16_rbt-base.sh具体内容哈

**Comment by Sally6651** [comment]
> 您好，还是麻烦您提供下环境细节（CUDA版本、pytorch版本），粘贴下具体的运行命令（请注意根据readme把`${DATAPATH}`替换成实际路径），并给下报错日志，这样可以便于我们尽快看下哈


 CUDA Version: 10.1  pytorch：2.0.0  运行命令：bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh /data/home/yaoyuan/Chinese-CLIP/DATA
运行脚本：
![751b3a0dfcc7973e2181bab2aa716c9](https://user-images.githubusercontent.com/132819872/236675447-31ca1bc8-fea0-4d0f-981e-9b2fd08e8b1f.png)
![b2ceb4eeeaf7512ece2e754df617486](https://user-images.githubusercontent.com/132819872/236675449-49081355-49ea-4bb6-b590-01bb5c357910.png)
报错日志：
![ccbab11eee08fd46138d6d8be6a38ca](https://user-images.githubusercontent.com/132819872/236675503-a2e030ec-9c63-45f4-a7b0-2c2e257d190f.png)

**Comment by Sally6651** [comment]
CUDA Version: 10.1 pytorch：2.0.0 运行命令：bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh /data/home/yaoyuan/Chinese-CLIP/DATA
运行脚本：
![1e994a22eefa389c496639e03420cb9](https://user-images.githubusercontent.com/132819872/236676358-39b84c37-9f9b-4a34-8251-43bb115697dc.png)
![cbe75b6498cd61d3e1764c832a52a22](https://user-images.githubusercontent.com/132819872/236676371-590f8d8c-7d66-461c-b10f-9be3635714df.png)
![9421ab42d08f66446ef37059d729b04](https://user-images.githubusercontent.com/132819872/236676374-59c4157c-fc52-4611-a377-711181a43451.png)
![9421ab42d08f66446ef37059d729b04](https://user-images.githubusercontent.com/132819872/236676385-0491448b-4f1a-4ac6-9991-55eeff521692.png)
报错日志：
![3f3df86143519e21478e9a82addce284_236675503-a2e030ec-9c63-45f4-a7b0-2c2e257d190f](https://user-images.githubusercontent.com/132819872/236676416-4f9b81da-868a-45be-9ec4-24c3b65c82a5.png)

**Comment by DtYXs** [comment]
您好，如果您是要在本机训练的话，建议您将`MASTER_ADDR`改为`localhost`，`MASTER_PORT`改为其他端口例如`8514`再试试看呢

**Comment by Sally6651** [comment]
您好，我按照您所说的进行操作了一下，还是在报错具体情况如下：
![1683523586481](https://user-images.githubusercontent.com/132819872/236741135-d323287b-cc93-4044-aa52-7fe27d974e3b.png)
![1683523593236](https://user-images.githubusercontent.com/132819872/236741174-f2407178-0195-4bac-8a46-114157d01319.png)
请问怎么解决呢，期待您的回复！

**Comment by yangapku** [comment]
您好，看最新的报错与NVIDIA驱动有关，建议您排查下机器GPU环境是否配置好（CUDA和NVIDIA驱动正确安装、pytorch为GPU版本），可以在python中执行`import torch;torch.ones(3,3).cuda() * 2;`这个简单的测试，看看pytorch目前GPU的支持情况是否正常

**Comment by duyz1234** [comment]
<img width="526" alt="8f18ce208dab821ccd55d2669b2d03a" src="https://user-images.githubusercontent.com/132811872/236750189-aa8cb26b-1c8a-46b4-b59e-b736d2922073.png">
是正常的！

**Comment by Sally6651** [comment]
您好，我按找您所给的python命令运行完后是这样的，请问可以用吗？
![1683527106801](https://user-images.githubusercontent.com/132819872/236750262-dcac21f2-d929-474f-af25-c9f7c1737daa.png)

**Comment by yangapku** [comment]
请问是否方便运行下以下命令提供一些信息呢？
```
import torch
print(torch.cuda.is_available())
print(torch.__version__)
print(torch.version.cuda)
```
初步根据您的描述和报错看上去，您的cuda版本对于pytorch2.0有些太低了，pytorch2.0正常情况下，需要11.7或11.8版本的cuda

**Comment by Sally6651** [comment]
您好，根据您所说的命令，我运行了一下
![404023322ea701211d93b37818f8526](https://user-images.githubusercontent.com/132819872/236754562-96a9c5a0-1121-4a72-a32c-8ef89b0c2d58.png)
CUDA版本：11.3

**Comment by yangapku** [comment]
好的，您运行的第二行和第三行命令输错了哈，可以直接粘贴我的代码再运行下。

方便的话，还可以运行下nvidia-smi截个图哈

**Comment by Sally6651** [comment]
非常抱歉，这是我重新运行后的结果
![404023322ea701211d93b37818f8526](https://user-images.githubusercontent.com/132819872/236759784-9b69e241-baab-46d5-9b24-256c7525e619.png)

**Comment by Sally6651** [comment]
不好意思
![d40e764d5f7e3aa6c10f7e35760554b](https://user-images.githubusercontent.com/132819872/236760025-38be0cf8-cb7f-4cab-b378-69fed4e6ad9f.png)

**Comment by yangapku** [comment]
方便跑下nvidia-smi命令，给个截图吗？

**Comment by yangapku** [comment]
方便的话，也运行下`which python`看下上面截图使用的python路径哈

**Comment by Sally6651** [comment]
![4766f7ea33d0d5109f019a3870d2865](https://user-images.githubusercontent.com/132819872/236764009-f6dd54c8-c61c-416d-a023-00516a189314.png)
![57744ab934be00d17b5d14bd32f1c97](https://user-images.githubusercontent.com/132819872/236764058-19b47ca9-fcb8-41b8-a0b7-ad4fa8bf7e98.png)

**Comment by yangapku** [comment]
您好，根据您最新的截图，我认为出问题的原因，是您在cuda 11.3版本+对应nvidia驱动上，安装运行了最低兼容cuda 11.6版本的pytorch（1.12.0+cu116）哈。建议您重新配置下anaconda环境，根据pytorch官网的介绍https://pytorch.org/get-started/previous-versions/ ，这次可以安装pytorch 1.12.1+cu113，`conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch`，之后再试一下
<img width="848" alt="image" src="https://user-images.githubusercontent.com/17445544/236766313-f5931405-6eba-4da9-af7d-03ff61527570.png">
