### ISSUE TITLE
执行bash命令报错

### ISSUE THREAD

**Issue by Sally6651** [OFA-Sys/Chinese-CLIP#99]
您好，我在执行bash命令时报错，具体如下：
![Uploading 1683526387801.png…]()
望您提供解决办法，期待您的回复！

**Comment by Sally6651** [comment]
![1683526387801](https://user-images.githubusercontent.com/132819872/236748265-06a5732d-be95-43f8-a0be-f484d5a4da51.png)

**Comment by yangapku** [comment]
您好，请参考issue #98 中我们同学的回复，`MASTER_ADDR`改为`localhost`，`MASTER_PORT`改为其他端口例如`8514`，试试看哈。主要还是`MASTER_ADDR`的问题，本机训练按照sh脚本的注释，应该写为`local_host`或`127.0.0.1`，不是机器的外网ip
